### ISSUE TITLE
Update Xerces to 2.12.1

### ISSUE THREAD

**Issue by fbricon** [eclipse/lemminx#1013]
https://github.com/eclipse/lemminx/blob/81298daf1d6aab4a5fd06fab3675affbf8fbff5d/org.eclipse.lemminx/pom.xml#L226

Xerces 2.12.1 was released on 12/01/2020. It includes a bunch of fixes (many related to XML 1.1). See http://xerces.apache.org/xerces2-j/releases.html

**Comment by angelozerr** [comment]
I wonder id this "standard" xerces bundle hosts the XML Schema 1.1 support? In previous version of Xerces the bundle did not provide this XML Schema 1.1 support (we had to use a non official release of xerces https://github.com/eclipse/lemminx/pull/515/files#diff-6fc26ced7fcf6efcf62ce3399da1f7b6cb28ae239db3a74d3cb6340fd5380fc6R104)

**Comment by datho7561** [comment]
I have run into issues with schema support when manually testing this

**Comment by angelozerr** [comment]
@datho7561 could you add in this issue all problems that you can encounter please. Thanks!

**Comment by datho7561** [comment]
Can't reproduce the issue.
