### ISSUE TITLE
Support for 'textDocument/selectionRange'

### ISSUE THREAD

**Issue by vemoo** [eclipse/lemminx#1021]
Link to spec: https://microsoft.github.io/language-server-protocol/specification#textDocument_selectionRange

Example of what it enables: https://rust-analyzer.github.io/manual.html#expand-and-shrink-selection

**Comment by angelozerr** [comment]
@vemoo could you give us a sample with XML please.

**Comment by vemoo** [comment]
This is how intellij idea does it:

https://user-images.githubusercontent.com/4866051/116423685-33c7ba00-a841-11eb-9c87-b7770fa5a4f6.mp4

But the simplest way to implement it I can think of is to locate the ast node at the cursor and then walk the parents until the root and return an array of the ranges of each of the nodes.

**Comment by angelozerr** [comment]
Thanks @vemoo for your demo, it's indeed a nice feature and should implement it.

**Comment by nitind** [comment]
The Java and XML Editors have this on their Edit menu, if anyone is looking for how the final presentation should appear.

**Comment by datho7561** [comment]
Thanks for pointing this out, nitind. GIF for reference:

![expand-selection-eclipse](https://user-images.githubusercontent.com/22376627/118991273-95b3a500-b951-11eb-94f3-24d2f947f992.gif)
