### ISSUE TITLE
Bad element formatting is replaced with <null>

### ISSUE THREAD

**Issue by rgrunber** [eclipse/lemminx#1034]
Takes a sampel with https://ejs.co/  syntax.

```xml
<foo>
  <url><%= url %></url>
</foo>
```

After formatting, we have:

```xml
<foo>
	<url>
		<null>
	</url>
</foo>
```

Currently the `<%` tags get replaced with `<null>`

**Comment by angelozerr** [comment]
This issue should be fixed by the experimental formatter https://github.com/redhat-developer/vscode-xml/blob/master/docs/Formatting.md#xmlformatexperimental
