### ISSUE TITLE
Preserve invalid content while formatting

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx#1041]
When formatting is done with invalid content theinvalid content is lost.

For instance given this XML content:

```xml
<a=
```

After formatting we lose the invalid content `=`

```xml
<a
```

There are several issues with this problem:

 * https://github.com/eclipse/lemminx/issues/1034
 * https://github.com/eclipse/lemminx/issues/679
 * https://github.com/eclipse/lemminx/issues/675
 * https://github.com/redhat-developer/vscode-xml/issues/624
 * 
and a PR which tries to fix the problem with invalid content inside  tag element https://github.com/eclipse/lemminx/pull/766

Today the formatting process load the XML content to format in a DOM Document and the DOM document is visited and we generate the XML content according DOM node type. At the end of the process we return ONE TextEdit which contains the generates XML string.

I think it's not the right way. Indeed after studying the formatting support in the WTP XML Editor (which preserve invalid content), the right way is to create several TextEdits (instead of one textedit) when a format must be done (ex : we create a TextEdit to format a start tag element to indent it, create N TextEdit  to format N start tag element to indent them).

See https://github.com/kingargyle/wtp-sourceediting/blob/master/plugins/org.eclipse.wst.xml.core/src/org/eclipse/wst/xml/core/internal/formatter/DefaultXMLPartitionFormatter.java from WTP which uses this strategy.

It's a lot of work, but IMHO I think we should do that to have a clean XML formatter.

**Comment by clementnuss** [comment]
fully agree with this issue, this is a "killer" for me at the moment, as I have to disable xml formatting altogether for the (many) documents where I use macros that insert credentials in xml fields.
these "macros" are not recognized by lemminx and replaced with `null` fields instead of being ignored.
commenting here to show the interest and to get notified of future improvements :)

**Comment by angelozerr** [comment]
This issue should be fixed by the experimental formatter https://github.com/redhat-developer/vscode-xml/blob/master/docs/Formatting.md#xmlformatexperimental
