### ISSUE TITLE
Send telemetry event when opening a file

### ISSUE THREAD

**Issue by fbricon** [eclipse/lemminx#1066]
When a file is opened, a telemetry event should be sent with
- file extension (.xml, .xsd, .classpath, ...)
- associated grammar:
      * none/xsd/dtd
      * local/remote
      * schema/grammar URL, if remote

we should be able to understand the popular content. If some schemas are used often that would give us some guidance on priorities.

**Comment by rgrunber** [comment]
Entry point would probably be https://github.com/eclipse/lemminx/blob/master/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/XMLTextDocumentService.java#L531 . From there, one can access the DOMDocument of the document being opened. It already has helper methods

**Comment by angelozerr** [comment]
@mauri-sfdc why are you confused? As @fbricon said, our goal is to give us some guidance on priorities. For instance if we see that :

 * there are a lot of xsl file which is opened, we could improve our basic XSL support.
 * there are a lot of dtd file which is opened, we could improve syntax coloration for DTD and improve DTD support again.
 * there are a lot of XML bound with RelaxNG files, we could start to implement RelaxNG support.

The telemetry will give us those relevant informations.

**Comment by angelozerr** [comment]
To know the referenced grammars, we should get list of [ReferencedGrammarInfo](https://github.com/eclipse/lemminx/blob/master/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/model/ReferencedGrammarInfo.java) from the opened, closed, etc DOM document.

```java
Set<ReferencedGrammarInfo> referencedGrammarInfos = contentModelManager.getReferencedGrammarInfos(document);
```

See sample at https://github.com/eclipse/lemminx/blob/81298daf1d6aab4a5fd06fab3675affbf8fbff5d/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/ContentModelSymbolsProviderParticipant.java#L73

You can see content of list of ReferencedGrammarInfo in Outline. With list of ReferencedGrammarInfo you will have know the list of bound XSD, DTD and for each binding you will know the binding type (catalog, files associations, xsi, doctype, etc) I think binding type is a relevant information too.

As ReferencedGrammarInfo belongs to the contentmodel extension (and not the core), the telemetry which will use ReferencedGrammarInfo must be done in the [contentmodel extension](https://github.com/eclipse/lemminx/tree/81298daf1d6aab4a5fd06fab3675affbf8fbff5d/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel).

To track didOpen, didClose, etc in an extension, you can do that with a lifecycle document participant. I created a PR for that in  (once https://github.com/eclipse/lemminx/pull/1091 

Once this PR will be merged, this issue could be done.
