### ISSUE TITLE
Incorrect error range for `src-import.3.2`

### ISSUE THREAD

**Issue by datho7561** [eclipse/lemminx#1069]
Given a schema:

```xml
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://example.org/my-example"
    xmlns:NS="http://example.org/my-example">
  <xs:import schemaLocation="./otherSchema.xsd"/>
</xs:schema>
```

and given that the schema file `otherSchema.xsd` exists and contains:

```xml
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://foo.bar"
>
  <xs:element name="root-element"></xs:element>
</xs:schema>
```

an error with the code `xsd(src-import.3.2)` is generated somewhere in the the starting tag of `<xs:schema>` in the first file. It would be nice if this error range instead covered the name of the `<xs:import>` element, or maybe even the value of the `schemaLocation` attribute of the `<xs:import>` element.

**Comment by AlexXuChen** [comment]
Hello
