### ISSUE TITLE
`linkedEditing` doesn't work with hyphens

### ISSUE THREAD

**Issue by datho7561** [eclipse/lemminx#1072]
eg.

```xml
<web-app|></web-app>
```

typing `le` to turn it into `web-apple` doesn't change the closing tag.

We can fix this on the language server side by providing a `wordPattern`: https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#linkedEditingRanges. This can also be configured in the client, although there may be benefits in configuring it on the server side.

**Comment by datho7561** [comment]
See microsoft/vscode#127334 for an example of a regular expression that could be used. It might make sense for each client to specify their own regular expression, since each client will likely use a different regular expression engine. Some might not support the unicode sequence that I used for the VS Code implementation.

**Comment by angelozerr** [comment]
The PR https://github.com/eclipse/lemminx/issues/1072 has been merged in vscode. Thanks @datho7561 !

This issue will be fixed with a new release of vscode. You can see this fix in vscode insider.

I close the issue.
