### ISSUE TITLE
Add support for remove end tag when closing in the same tag

### ISSUE THREAD

**Issue by gayanper** [eclipse/lemminx#1081]
Take the following example

`<bean class="java.util.ArrayList"></bean>`

when I change this to 

`<bean class="java.util.ArrayList"/></bean>`

I expect the editor to remove the end tag and complete the line as

`<bean class="java.util.ArrayList"/>`

**Comment by fbricon** [comment]
This is a limitation of the Eclipse integration. It works fine with vscode.

**Comment by gayanper** [comment]
Is it a LSP4E limitation?

**Comment by fbricon** [comment]
Well this requires the clients to support the [autoclose](https://github.com/eclipse/lemminx/issues/82) request, which is not part of the standard LSP4J protocol. The Lemminx integration in Eclipse would need to support that custom command.

**Comment by angelozerr** [comment]
@gayanper please create an issue in wwd.

There is the same problem in wwd with html. Wwd must implement custom lsp request.

Please note that lemminx need to refactor and  hange the lsp request to have the same lsp request than html.

In otherwords I suggest that wwd implement the lsp request for html and Once lemminx will  implement the same lsp request than html it will be easy for wwd to support auto close and double quote insert when you type = in html and xml both.

I close the issue.

**Comment by gayanper** [comment]
> @gayanper please create an issue in wwd.
> 
> There is the same problem in wwd with html. Wwd must implement custom lsp request.
> 
> Please note that lemminx need to refactor and hange the lsp request to have the same lsp request than html.
> 
> In otherwords I suggest that wwd implement the lsp request for html and Once lemminx will implement the same lsp request than html it will be easy for wwd to support auto close and double quote insert when you type = in html and xml both.
> 
> I close the issue.

Sure @angelozerr
