### ISSUE TITLE
LemMinX doesn't declare workspaceFolders capability

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lemminx#1110]
Since #293 , LemMinX supports workspace folders very well (we have tests in lemminx-maven about that).
However, I just realized that the capability is not declared so that standard clients will assume workspace folders are not supported and hence won't send workspaceFolders notifications.

**Comment by angelozerr** [comment]
Fixed with https://github.com/eclipse/lemminx/pull/1111
