### ISSUE TITLE
how code complete to groupId、artifactId、version in maven pom.xml 

### ISSUE THREAD

**Issue by zcjava** [eclipse/lemminx#1113]
i use lsp-java wriite maven java project. how i use lsp-java company-capf implementation like idea func :
![image](https://user-images.githubusercontent.com/1551382/132095679-839e8c60-713e-42e3-b1f5-69b28286b293.png)

**Comment by mickaelistria** [comment]
Specific support for Maven pom files is provided by the lemminx-maven extension, which is available at https://github.com/eclipse/lemminx-maven .
