### ISSUE TITLE
Entities in grammars don't seem to be fully evaluated

### ISSUE THREAD

**Issue by enxio** [eclipse/lemminx#1122]
I have the following two dtds:

d1.dtd:

```XML
<?xml version="1.0" encoding="UTF-8"?>
<!ENTITY % d2 SYSTEM "d2.dtd"> 
%d2;

<!--
element demo
-->
<!ELEMENT demo
    (
    foo?,
    bar?
    )>
```

and d2.dtd

```XML
<!-- 
foo element
-->
<!ELEMENT foo (#PCDATA)>

<!--
bar element
-->
<!ELEMENT bar (#PCDATA)>
```

and the XML document:

```XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE demo SYSTEM "http://loc/d1.dtd">
<demo>
   <foo></foo>
   <bar></bar>
</demo> 
```

Now, in VS Code I get both `foo` and `bar` opening tags underlined with red squigglies showing the following:

```
Element type "bar" must be declared.xml(MSG_ELEMENT_NOT_DECLARED)
bar element
```

If I "pull up" the DTDs into one and get rid of entity "inclusion", then the squigglies go away. 

Completion works as expected though in every case.

Could this be a problem in the language server?

Thanks for your consideration.

**Comment by enxio** [comment]
Yup, that does the trick. Thanks a lot!

**Comment by angelozerr** [comment]
> Yup, that does the trick. Thanks a lot!

Glad it works for you.
