### ISSUE TITLE
High memory usage with latest version of XMLanguage server

### ISSUE THREAD

**Issue by gayanper** [eclipse/lemminx#1129]
Version of the WildWebDeveloper XML Version

```
Eclipse Wild Web Developer project	XML support using Language Server	0.13.1.202111081705	org.eclipse.wildwebdeveloper.xml
```
Running with : java.vendor.version=Temurin-17+35

Opening a XML take the memory from 500MB to 6GB within minutes and the whole time the editor is frozen.

**Comment by gayanper** [comment]
I think this is related to lemmnix maven extension. Will investigate and move the bug.

**Comment by gayanper** [comment]
reported https://github.com/eclipse/lemminx-maven/issues/234

**Comment by gayanper** [comment]
I think we should introduce a max heap flag to configure the amount through eclipse.ini at least like the STS4 LS does.

**Comment by mickaelistria** [comment]
Issue is not in LemMinX: fix would be in LemMinX-Maven and a customization flag would be in Wild Web Developer; let's close.
