### ISSUE TITLE
XML validation failing

### ISSUE THREAD

**Issue by claudioweiler** [eclipse/lemminx#1130]
I have some XML validations failing constantly.

**Files:** 

- web.xml
- faces-config.xml

**Error message on web-app definition**

> _There is '1' error in 'javaee_?.xsd'._ (? could be 7 or 8)

**Warning message on xsi:schemaLocation definition**

> _schema_reference.4: Failed to read schema document 'platform:/plugin/org.eclipse.xsd/cache/www.w3.org/
 2001/xml.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element 
 of the document is not <xsd:schema>._

**Tests**

1. Open Eclipse;
2. Open file (web.xml or faces-config.xml, or both)
3. Validation error
4. Break file (remove 1 important line), save
5. Correct file, save
6. Validation OK
7. Restart Eclipse:  validation errors back

**Environment**

- I have a folder "~/.lemminx/cache" with files referenced above.
- Eclipse 2021-06
- Java 11
- Windows 10

**Samples**

```xml
<?xml version="1.0" encoding="UTF-8"?>
<web-app
    version="4.0"
    xmlns="http://xmlns.jcp.org/xml/ns/javaee"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_4_0.xsd">
[...]
</web-app>
```
```xml
<?xml version="1.0" encoding="UTF-8"?>
<faces-config
    version="2.3"
    xmlns="http://xmlns.jcp.org/xml/ns/javaee"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-facesconfig_2_3.xsd">
[...]    
</faces-config>
```

p.s.
I don't know if this is related, but it identifies web-app (servlet) version 4 as Java EE 7, when it is [Java EE 8](https://www.oracle.com/java/technologies/java-ee-8.html)

**Comment by angelozerr** [comment]
I close this issue since it's an issue from integration of LemMinX inside Eclipse IDE with WWD. 

If I remember it should be fixed https://github.com/eclipse/wildwebdeveloper/pull/726

**Comment by claudioweiler** [comment]
Ok, thanks @angelozerr.

I see that this is merged on version 13.0, probably will be available on Eclipse [2021-12](https://download.eclipse.org/releases/2021-12/202112081000/plugins/), I will test it on release.

About this:
> I don't know if this is related, but it identifies web-app (servlet) version 4 as Java EE 7, when it is Java EE 8

It is LemMinX related?

**Comment by angelozerr** [comment]
> It is LemMinX related?

What do you mean with identifies web-app?

**Comment by claudioweiler** [comment]
The 1st sample code above: `<web-app version="4.0" ... >` (web.xml file).

Validation error message comes with `There is '1' error in 'javaee7.xsd'`, but it should be Java EE 8.

**Comment by angelozerr** [comment]
I think XSD includes javaee7.xsd? LemMinX load just XSD without any context like Java EE,etc

**Comment by claudioweiler** [comment]
Maybe it's another plugin that handles this. Just for note, here are the original xsd files: https://www.oracle.com/webfolder/technetwork/jsc/xml/ns/javaee/index.html

I try to find any descriptive relation between xsds, but find none.

Anyway, this is a minor issue, that probably do not cause any harm.

Thanks!

**Comment by TechRaviPandey990** [comment]
Downloading external resources is disabled.	
There is '1' error in 'jakartaee_10.xsd'.
I am getting these two problems in Web.Xml . Can anyone help me how to get rid of these problems . I am using Tomcat 10.1
