### ISSUE TITLE
Unable to work with modular DTD?

### ISSUE THREAD

**Issue by lpanebr** [eclipse/lemminx#1141]
## Problem
**When editing a file with correct DOCTYPE and available DTD files I get message saying the DTD has 41 errors:**
![image](https://user-images.githubusercontent.com/129185/147365463-c1da8ec2-7686-4e96-8d9b-21ffc4c6f781.png)

The DTD in question is the [JATS (Journal Article Tagging Suite)](https://jats.nlm.nih.gov/index.html), which is a NISO Z39.96-2019 standard maintained by the NLM (U.S. National Library of Medicine), and it most certainly does not have any errors.

**I feel that the server is working, for when I remove the system identifier I get the correct error:**
![image](https://user-images.githubusercontent.com/129185/147365588-c1e56eca-68fe-4443-ac98-48c7de25139e.png)

**Please, any ideas as to what might be wrong?**

## DTD library and test file
This DTD is available at
ftp://ftp.ncbi.nih.gov/pub/jats/publishing/1.1d3/JATS-Publishing-1-1d3-MathML2-DTD.zip
and is composed of the following files, which include a sample test XML file (marked below).
```bash
./
├── catalog-jats-v1-1d3-no-base.xml
├── catalog-jats-v1-1d3-with-base.xml
├── iso8879
│   ├── isobox.ent
│   ├── isocyr1.ent
│   ├── isocyr2.ent
│   ├── isodia.ent
│   ├── isolat1.ent
│   ├── isolat2.ent
│   ├── isonum.ent
│   └── isopub.ent
├── iso9573-13
│   ├── isoamsa.ent
│   ├── isoamsb.ent
│   ├── isoamsc.ent
│   ├── isoamsn.ent
│   ├── isoamso.ent
│   ├── isoamsr.ent
│   ├── isogrk3.ent
│   ├── isomfrk.ent
│   ├── isomopf.ent
│   ├── isomscr.ent
│   └── isotech.ent
├── JATS-ali-namespace1.ent
├── JATS-articlemeta1.ent
├── JATS-backmatter1.ent
├── JATS-chars1.ent
├── JATS-common1.ent
├── JATS-common-atts1.ent
├── JATS-default-classes1.ent
├── JATS-default-mixes1.ent
├── JATS-display1.ent
├── JATS-format1.ent
├── JATS-funding1.ent
├── JATS-journalmeta1.ent
├── JATS-journalpubcustom-classes1.ent
├── JATS-journalpubcustom-mixes1.ent
├── JATS-journalpubcustom-models1.ent
├── JATS-journalpubcustom-modules1.ent
├── JATS-journalpublishing1.dtd
├── JATS-link1.ent
├── JATS-list1.ent
├── JATS-math1.ent
├── JATS-mathml3-mathmlsetup1.ent
├── JATS-mathml3-modules1.ent
├── JATS-mathmlsetup1.ent
├── JATS-modules1.ent
├── JATS-nlmcitation1.ent
├── JATS-notat1.ent
├── JATS-oasis-namespace1a.ent
├── JATS-oasis-namespace1.ent
├── JATS-oasis-tablesetup1.ent
├── JATS-para1.ent
├── JATS-phrase1.ent
├── JATS-references1.ent
├── JATS-related-object1.ent
├── JATS-section1.ent
├── JATS-XHTMLtablesetup1.ent
├── JATS-xmlspecchars1.ent
├── mathml
│   ├── mmlalias.ent
│   └── mmlextra.ent
├── mathml2.dtd
├── mathml2-qname-1.mod
├── mathml3.dtd
├── mathml3-qname1.mod
├── oasis-exchange.ent
├── Smallsamples
│   ├── journal.elementa.000011.xml
│   ├── journal.elementa.000012.xml
│   ├── journal.elementa.000017.xml
│   └── samplesmall-pub1.xml                                          # this is the test file
├── xhtml-inlstyle-1.mod
├── xhtml-table-1.mod
└── xmlchars
    ├── isogrk1.ent
    ├── isogrk2.ent
    └── isogrk4.ent
```

**Comment by angelozerr** [comment]
If you open the dtd have you some errors? Please note that if you open your xml in vscode-xml  you should see the detail if your 41 errors

**Comment by lpanebr** [comment]
Thanks for  your reply.

### in neovim
I get the following diagnostics **for the sample XML file**:
![image](https://user-images.githubusercontent.com/129185/147570649-dc2ab0eb-ecfe-4964-a579-416d30cee28b.png)

but nothing when I open the DTD main file `JATS-journalpublishing1.dtd`.

I noticed however that the Lemminx server is not configured for the `.dtd` filetype... Should it be?
![image](https://user-images.githubusercontent.com/129185/147569673-33f2e7ec-12a9-4c99-ac04-9a66e74b02c8.png)


### in vscode
With the [redhat vscode-xml plugin](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml) I get the following diagnostics for the **sample XML file**:

![image](https://user-images.githubusercontent.com/129185/147571253-258c4e0f-3d63-4073-bcea-f7fc0327ac7e.png)

and also nothing when I open the DTD main file `JATS-journalpublishing1.dtd`.


🤔 **Now that I tested a bit more**

Both editors seem to be correctly reading the DTD as they show information from specific elements:

**neovim:**
![image](https://user-images.githubusercontent.com/129185/147621833-be18d642-f15c-430f-a417-aad4b8b05b96.png)

**vscode:**
![image](https://user-images.githubusercontent.com/129185/147621929-cd13ba64-2b7b-4c3c-a678-1376fed1405b.png)

ACTUALLY they are both working and suggesting correct elements, attributes and even attribute values from the DTD.

**But then why are they such a lot of errors?** Is it some Lemminx bug?

**Comment by angelozerr** [comment]
Thanks @lpanebr for your great explanation and feedback.

I need some time to study in detail your problem.

**Comment by angelozerr** [comment]
> I noticed however that the Lemminx server is not configured for the .dtd filetype... Should it be?

I think.

**Comment by angelozerr** [comment]
@lpanebr could you share a zip which contains your vscode project with dtd and some xml file. Thanks

**Comment by lpanebr** [comment]
Sure @angelozerr 
Thanks for all the attention!

I've attached the [jats-dts-and-sample-files.zip](https://github.com/eclipse/lemminx/files/7788760/jats-dts-and-sample-files.zip) file.

The test files are inside the `Smallsamples` directory.

Please note that they use the systemID relative path because for some reason I'm unable to get the catalogs to work... 😞 (I haven't created an issue cause I feel it's y fault.. if you perhaps have any tips on that I'd greatly appreciate it)

**Comment by angelozerr** [comment]
Thanks for the zip, I understand now your problem, you need to enable resolve extrenal entities because by default entities are not resolved:

![image](https://user-images.githubusercontent.com/1932211/147669932-d8f09b30-c3f1-4f6b-8d56-6dfb682b6f58.png)

Once you will enable it, close your vscode and restart it and it should work. See https://github.com/redhat-developer/vscode-xml/wiki/XMLValidation#resolve-external-entities

**Comment by deathaxe** [comment]
The zip file contains a folder `Smallsamples`. All contained files point to the correct DTD file using relative file paths.

see: 1.1/Smallexamples/samplesmall-pub1.xml

```xml
<!DOCTYPE article PUBLIC "-//NLM//DTD JATS (Z39.96) Journal Publishing DTD v1.1d3 20150301//EN" "../JATS-journalpublishing1.dtd">
```

Lemminx resolves the DTD source via `"../JATS-journalpublishing1.dtd"`.

Changing this entry by removing `../` will cause the DTD no longer to be found/resolved.

_Tried that with both ST an VSCode with `"xml.validation.resolveExternalEntities": true,`._

**Comment by angelozerr** [comment]
> My understanding is that the SYSTEM ID shouldn't need to be relative to the XML file which references it. 

It's the behavior without XML catalog.

> Instead both the PUBLIC and SYSTEM ID should be looked up in the catalog. 

Exactly, if you try with vscode-xml and you configure the XML catalogs like this


```
"xml.catalogs": [
      "catalog-jats-v1-1d3-no-base.xml"
   ]
```

It should work no?

**Comment by deathaxe** [comment]
Appears I've choosen the wrong file. Configuring the `catalog-jats-v1-1d3-no-base.xml` seems to work.

**Comment by angelozerr** [comment]
> Configuring the catalog-jats-v1-1d3-no-base.xml seems to work.

Great!

I'm waiting for feedback from @lpanebr to know if this issue is resolved?

**Comment by lpanebr** [comment]
Hi guys, thank you so much for the help!

**Setting the setting below made it all good in VSCode!** 🤩
![image](https://user-images.githubusercontent.com/129185/147688719-575a7bd5-000b-4c55-b145-5e3745d9e5c4.png)
![image](https://user-images.githubusercontent.com/129185/147688759-353e7576-07e3-4494-9e6f-e2175a231fe6.png)

So I guess I was right. It was (and still is) all my fault not knowing how to configure my IDEs... 🤦

The only thing missing for my complete happiness is to get it working also on Sublime Text and on Neovim.

@deathaxe **did you get it to work on Sublime Text?**

**Comment by lpanebr** [comment]
I got it working on Sublime Text!
```json
{
	"settings":
	{
		"xml.catalogs": [
			"/home/lpanebr/catalogs/catalog.xml"
		],
		"xml.validation.resolveExternalEntities": true,
	}
}
```
I guess Neovim is only a matter of time now!

**Comment by lpanebr** [comment]
Still having a hard time with Neovim, but I've checked the log and found this:
```
[WARN][2021-12-29 16:47:17] ...lsp/handlers.lua:109     "The language server lemminx triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
```

**Should I create an issue?**

**Comment by lpanebr** [comment]
I did it!!!!

In case anyone ever needs to set up Lemminx via [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) in Neovim, here's how to pass settings to the config:

```lua
      xml = {
        catalogs = { "/home/lpanebr/catalogs/catalog.xml" },
        validation =  { 
          resolveExternalEntities = true
        }
      }
```

I'll send a PR so that this gets added to the [nvim-lspconfig server_configurations example for lemminx](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#lemminx).

Thank you so much again! This non-issue is resolved.

**Comment by fbricon** [comment]
> Still having a hard time with Neovim, but I've checked the log and found this:
> 
> ```
> [WARN][2021-12-29 16:47:17] ...lsp/handlers.lua:109     "The language server lemminx triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
> ```
> 
> **Should I create an issue?**

Yes please, in https://github.com/eclipse/lemminx/issues

**Comment by deathaxe** [comment]
@lpanebr Do you really get diagnostics and completions in Sublime Text?

While I don't see any errors about missing declarations, no completions, hover popups nor diagnostics are provided. It appears, LemMinX ignores everything from the linked DTD file for some unknown reason.

The following providers are registered dynamically:

```
LSP: LemMinX: registering capability: codeActionProvider
LSP: LemMinX: registering capability: completionProvider
LSP: LemMinX: registering capability: documentHighlightProvider
LSP: LemMinX: registering capability: hoverProvider
LSP: LemMinX: registering capability: renameProvider
LSP: LemMinX: registering capability: definitionProvider
LSP: LemMinX: registering capability: typeDefinitionProvider
LSP: LemMinX: registering capability: referencesProvider
LSP: LemMinX: registering capability: documentFormattingProvider
LSP: LemMinX: registering capability: rangeFormattingProvider
LSP: LemMinX: registering capability: selectionRangeProvider
LSP: LemMinX: registering capability: documentSymbolProvider
LSP: LemMinX: registering capability: executeCommandProvider
```

LemMinX provides some basic completions (e.g.: `<!-- #region $1-->`), but doesn't include anything from the linked DTD file.

```
:: --> LemMinX textDocument/completion(183): {'textDocument': {'uri': 'file:///C:/Data/catalogs/1.1/Smallsamples/test2.xml'}, 'position': {'line': 2, 'character': 0}}
:: <<< LemMinX 183: {'isIncomplete': False, 'items': [{'kind': 15, 'sortText': 'za', 'documentation': 'Insert Folding Region Start', 'filterText': '', 'textEdit': {'range': {'start': {'line': 2, 'character': 0}, 'end': {'line': 2, 'character': 0}}, 'newText': '<!-- #region $1-->'}, 'label': '#region', 'insertTextFormat': 2}, {'kind': 15, 'sortText': 'zb', 'documentation': 'Insert Folding Region End', 'filterText': '', 'textEdit': {'range': {'start': {'line': 2, 'character': 0}, 'end': {'line': 2, 'character': 0}}, 'newText': '<!-- #endregion-->'}, 'label': '#endregion', 'insertTextFormat': 1}, {'kind': 15, 'sortText': 'model', 'insertTextFormat': 2, 'documentation': {'kind': 'markdown', 'value': '\r\n```\r\n<?xml-model href="file.xsd" type="application/xml" schematypens="http://www.w3.org/2001/XMLSchema"?>\r\n```\r\n'}, 'filterText': '<?xml-model', 'textEdit': {'range': {'start': {'line': 2, 'character': 0}, 'end': {'line': 2, 'character': 0}}, 'newText': '<?xml-model href="${1:file.xsd}" type="application/xml" schematypens="http://www.w3.org/2001/XMLSchema"?>${0}'}, 'label': 'Insert XML Schema association', 'detail': 'Insert XML Model Processing Instruction to Associate XSD Schema'}, {'kind': 15, 'sortText': 'model', 'insertTextFormat': 2, 'documentation': {'kind': 'markdown', 'value': '\r\n```\r\n<?xml-model href="file.dtd" type="application/xml-dtd"?>\r\n```\r\n'}, 'filterText': '<?xml-model', 'textEdit': {'range': {'start': {'line': 2, 'character': 0}, 'end': {'line': 2, 'character': 0}}, 'newText': '<?xml-model href="${1:file.dtd}" type="application/xml-dtd"?>${0}'}, 'label': 'Insert DTD association', 'detail': 'Insert XML Model Processing Instruction to Associate Document Type Description (DTD)'}, {'kind': 15, 'sortText': 'stylesheet', 'insertTextFormat': 2, 'documentation': {'kind': 'markdown', 'value': '\r\n```\r\n<?xml-stylesheet href="file.xsl" type="text/xsl"?>\r\n```\r\n'}, 'filterText': '<?xml-stylesheet', 'textEdit': {'range': {'start': {'line': 2, 'character': 0}, 'end': {'line': 2, 'character': 0}}, 'newText': '<?xml-stylesheet href="${1:file.xsl}" type="text/xsl"?>${0}'}, 'label': 'Insert XSL Stylesheet association', 'detail': 'Insert XML Stylesheet Processing Instruction to Associate XSL Transformation Stylesheet (XSLT)'}, {'kind': 15, 'sortText': 'stylesheet', 'insertTextFormat': 2, 'documentation': {'kind': 'markdown', 'value': '\r\n```\r\n<?xml-stylesheet href="file.css" type="text/css"?>\r\n```\r\n'}, 'filterText': '<?xml-stylesheet', 'textEdit': {'range': {'start': {'line': 2, 'character': 0}, 'end': {'line': 2, 'character': 0}}, 'newText': '<?xml-stylesheet href="${1:file.css}" type="text/css"?>${0}'}, 'label': 'Insert CSS Stylesheet association', 'detail': 'Insert XML Stylesheet Processing Instruction to Associate Cascading Stylesheet (CSS)'}]}
```

I also don't see diagnostics.

![grafik](https://user-images.githubusercontent.com/16542113/147748243-7846e45c-e01a-499a-89dd-bedd91022edd.png)

It's working in VS Code though.

![grafik](https://user-images.githubusercontent.com/16542113/147748280-189abf0f-e9e7-4eba-a6ab-e7ea0c4e6d99.png)

I checked configuration (compared VS Code and ST).

Comparing server traces doesn't reveal something obvious as well.

Some hints about required preconditions would be appriciated.

@rwols: Maybe LSP plugin is missing something?

**Comment by lpanebr** [comment]
@deathaxe yeah, I get errors, warnings, element descriptions, popup and rename. Check it out.

## This is what I have now
Note that the DOCTYPE in the file I'm using belo does not use URL nor relative path SYSTEM ID. The file in in my desktop far from the DTD files. **Sublime is finding the DTD files through the PUBLIC ID I've configured in the catalog file.**
![image](https://user-images.githubusercontent.com/129185/147759907-d2f55fe7-2f21-47d0-801d-138b98286fa3.png)


Here you see the error and description for the `journal-meta` element. While the "Source" in the popup takes us only to the DTD main file, the actual model and element description are combined from the `JATS-journalmeta1.ent` and `JATS-default-classes1.ent` files.
![image](https://user-images.githubusercontent.com/129185/147755234-b4e86a1c-6bbd-424f-aed2-9797172c865f.png)

Below I've removed the `journal-id` elements and as soon as I type `<` I get suggested elements for this specific context (`journal-meta`).
![image](https://user-images.githubusercontent.com/129185/147756530-36934591-7a2c-4714-ace8-32d9f9a4b1de.png)

After adding the `journal-id` element and typing a space I get **context aware attribute suggestions** with **attribute description** when clicking the "more" link at the bottom of the popup!
![image](https://user-images.githubusercontent.com/129185/147757472-6c3601ca-92b3-4074-a5d5-df10049b2d2d.png)

And finally, for the cherry on top of the cake, I get **attribute value suggestions** for the attributes that have them in the DTD (that's why I used other element for this image).
![image](https://user-images.githubusercontent.com/129185/147757975-7b0c1aa2-b73e-4e25-878b-e85bdceb2599.png)

## **To get that working I have:**

**Sublime Text 4 with the following plugins:**
 - **Exalt**
 - **Lemminx** with the configuration `LSP-lemminx.sublime-settings` below

**Local catalog file and corresponding DTD files:**
 - `/home/lpanebr/catalogs/catalog.xml` below

## Sublime `LSP-lemminx.sublime-settings`
```json
{
	"settings":
	{
		"xml.catalogs": [
			"/home/lpanebr/catalogs/catalog.xml"
		],
		"xml.validation.resolveExternalEntities": true,
		"xml.completion.autoCloseTags": true,
		"xm
}
```

##  Local catalog file and corresponding DTD files
`/home/lpanebr/catalogs/catalog.xml`
```xml
<?xml version="1.0"?>
<!DOCTYPE catalog PUBLIC "-//OASIS//DTD Entity Resolution XML Catalog V1.0//EN" "http://www.oasis-open.org/committees/entity/release/1.0/catalog.dtd">
<catalog prefer="public" xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">

  <public 
    publicId="-//NLM//DTD JATS (Z39.96) Journal Publishing DTD v1.1 20151215//EN" 
    uri="/home/lpanebr/catalogs/jats/dtd/1.1/JATS-journalpublishing1.dtd" />
  <public 
    publicId="-//NLM//DTD JATS (Z39.96) Journal Publishing DTD v1.1d3 20150301//EN" 
    uri="/home/lpanebr/catalogs/jats/dtd/1.1d3/JATS-journalpublishing1.dtd" />

  <public 
    publicId="-//NLM//DTD JATS (Z39.96) Journal Publishing DTD v1.0 20120330//EN" 
    uri="/home/lpanebr/catalogs/jats/dtd/1.0/JATS-journalpublishing1.dtd" />

</catalog>
```

**Corresponding DTD files:**
[JATS (Journal Article Tagging Suite) DTD](https://jats.nlm.nih.gov/index.html) files are available at:
https://ftp.ncbi.nih.gov/pub/jats/publishing/
```
/home/lpanebr/catalogs/
├── catalog.xml
└── jats
    └── dtd
        ├── 1.0
        │   ├── iso8879
        │   ├── iso9573-13
        │   ├── mathml
        │   ├── Smallsamples
        │   └── xmlchars
        ├── 1.1
        │   ├── iso8879
        │   ├── iso9573-13
        │   ├── mathml
        │   └── xmlchars
        └── 1.1d3
            ├── iso8879
            ├── iso9573-13
            ├── mathml
            ├── Smallsamples
            └── xmlchars
```

If you can please try the config as shown above and see if it works. 
If not let me know and I'll be happy to try to help.

**Comment by deathaxe** [comment]
My configuration used to be

```json
	"settings":
	{
		"xml.catalogs": [
			"C:\\Data\\catalogs\\JATS-3\\catalog-v3.xml",
			"C:\\Data\\catalogs\\1.1\\catalog-jats-v1-1d3-no-base.xml",
		],
		"xml.validation.resolveExternalEntities": true
	}
```

When removing `"C:\\Data\\catalogs\\JATS-3\\catalog-v3.xml",` or moving it down one line, diagnostics start working.

I wouldn't have expected that entry to cause any trouble as it doesn't contain a definition for the PUBLIC ID nor SYSTEM ID of the open xml document.

Lemminx registered both catalogs without errors or warnings. I wonder, whether there are issues when working with multiple catalogs at a time.

**Comment by lpanebr** [comment]
I've just helped a colleague that uses windows and you need to use `/` instead of `\\`:
 - `C:/Data/catalogs/JATS-3/catalog-v3.xml`

Remember to adjust also in the catalog:
```xml
<?xml version="1.0"?>
<!DOCTYPE catalog PUBLIC "-//OASIS//DTD Entity Resolution XML Catalog V1.0//EN" "http://www.oasis-open.org/committees/entity/release/1.0/catalog.dtd">
<catalog prefer="public" xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">

  <!-- Windows -->
  <public 
    publicId="-//NLM//DTD JATS (Z39.96) Journal Publishing DTD v1.1 20151215//EN" 
    uri="C:/catalog/jats/dtd/1.1/JATS-journalpublishing1.dtd" />
  <system 
    systemId="https://jats.nlm.nih.gov/publishing/1.1/JATS-journalpublishing1.dtd" 
    uri="C:/catalog/jats/dtd/1.1/JATS-journalpublishing1.dtd" />

  <!-- Linux -->
  <!-- <public 
    publicId="-//NLM//DTD JATS (Z39.96) Journal Publishing DTD v1.1 20151215//EN" 
    uri="/home/lpanebr/catalogs/jats/dtd/1.1/JATS-journalpublishing1.dtd" />
  <system 
    systemId="https://jats.nlm.nih.gov/publishing/1.1/JATS-journalpublishing1.dtd" 
    uri="/home/lpanebr/catalogs/jats/dtd/1.1/JATS-journalpublishing1.dtd" /> -->

</catalog>

```


**Also note that I built this catalog by hand instead of using those provided with the DTD library.**

**Comment by deathaxe** [comment]
> I've just helped a colleague that uses windows and you need to use `/` instead of `\\`

Backslashes are working fine on Windows. This is not an issue at all.

> Also note that I built this catalog by hand instead of using those provided with the DTD library.

Sure, but the included `catalog-jats-v1-1d3-no-base.xml` works very well, if it is the only one in the `catalogs` list.

Absolute paths shouldn't be needed in catalog files as all `uri`'s are resolved relative to the location of the catalog.xml.

---

It appears, if anything goes wrong with registering a catalog.xml all following entries in the list are ignored. Sometimes silently, sometimes with errors.

I have a set of local schemes organized with catalogs. If I put the main catalog into the settings file, LemMinX stops loading the JATS catalog.

```json
		"xml.catalogs": [
			"C:\\Data\\Sublime\\XML\\schemas\\catalog.xml",
			"C:\\Data\\catalogs\\1.1\\catalog-jats-v1-1d3-no-base.xml",
		],
```

**C:/Data/Sublime/XML/schemas/catalog.xml**

```xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE catalog PUBLIC "-//OASIS//DTD XML Catalogs V1.1//EN"
                         "http://www.oasis-open.org/committees/entity/release/1.1/catalog.dtd">
<catalog prefer="public" xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
  <nextCatalog catalog="fo/catalog.xml"/>
<!--   <nextCatalog catalog="focheck/catalog.xml"/>
  <nextCatalog catalog="jsp/catalog.xml"/>
  <nextCatalog catalog="plist/catalog.xml"/>
  <nextCatalog catalog="sublime/catalog.xml"/>
  <nextCatalog catalog="svg/catalog.xml"/>
  <nextCatalog catalog="xinclude/catalog.xml"/>
  <nextCatalog catalog="xlink/catalog.xml"/>
  <nextCatalog catalog="xml/catalog.xml"/>
  <nextCatalog catalog="xmlschema/catalog.xml"/>
  <nextCatalog catalog="xmltransform/catalog.xml"/>
 -->
 </catalog>
```

LemMinx returns

```
LemMinX: Dec 30, 2021 05:42:17 org.eclipse.lemminx.extensions.contentmodel.uriresolver.XMLCatalogResolverExtension setCatalogs()
Message: Adding XML catalog 'C:\Data\Sublime\XML\schemas\catalog.xml' with expand system id 'file:///C:/Data/Sublime/XML/schemas/catalog.xml' and root URI 'file:///C:/Data/catalogs/1.1/'.
LemMinX: Dec 30, 2021 05:42:17 org.eclipse.lemminx.extensions.contentmodel.uriresolver.XMLCatalogResolverExtension setCatalogs()
Message: Adding XML catalog 'C:\Data\catalogs\1.1\catalog-jats-v1-1d3-no-base.xml' with expand system id 'file:///C:/Data/catalogs/1.1/catalog-jats-v1-1d3-no-base.xml' and root URI 'file:///C:/Data/catalogs/1.1/'.
```

Everything looks, fine! But the PUBLIC ID is no longer resolved. SYSTEM ID points to wrong location.

![grafik](https://user-images.githubusercontent.com/16542113/147771394-e7c390cd-3420-4f91-9c13-79127ee47c75.png)

At some point LemMinX seems to give up too early. All catalogs point to correct files. They have been working fine with Exalt, which I replaced by LemMinX.

**Comment by lpanebr** [comment]
I'm confused as to why both catalogs are being added with the same root URI in your log output?
```
LemMinX: ...
Message: Adding ... 'C:\Data\Sublime\XML\schemas\catalog.xml' with ... and root URI 'file:///C:/Data/catalogs/1.1/'.
LemMinX: ...
Message: Adding ... 'C:\Data\catalogs\1.1\catalog-jats-v1-1d3-no-base.xml' with ... and root URI 'file:///C:/Data/catalogs/1.1/'.
```

Is that correct?

**Comment by deathaxe** [comment]
I think the root URI is the workspace's path. The C:\Data\catalogs\1.1\ folder is the one open in ST.

**Comment by lpanebr** [comment]
oh man... just had a major set back while trying to help that colleague that uses windows.. we're basically were I started.. 

If we enable the plugins as I have described (and as works in my linux OS), both Sublime and VS Code behave erratically not finding the DTD.

In Sublime it gets partially OK if we only install the Exalt plugin. We then get suggestions but not context aware... :-/

In VS Code I with the redhat plugin we could not make it work and always get either DTD not found or 41 errors in the DTD (which I thought was to be fixed by the enable external references.... but it did not)... :-(

**Comment by deathaxe** [comment]
Everything is fine for me, if I only add your jats-1.1 catalog. Note, I use the  `catalog-jats-v1-1d3-no-base.xml` without the `base="/.../"` entries. As soon as I start adding further catalogs to the settings file, trouble starts.

_Note: I think, Exalt is no longer needed as LemMinX provides both, validation and completions._

The main issue is, that if something goes wrong with parsing catalogs or resolving uris, no error is output somewhere. We don't see any hints about what's wrong, but expected functions to stop working only.

The catalog of the JATS-3 schemes I've downloaded, contains a lot of entries, which don't exist in the folder. This error seems to cause LemMinX to drop entries from all following catalogs, when resolving external uri's.

It should log some errors while loading catalogs, if something can't be resolved. Or it should do so, when resolving uri's.

It's indeed somewhat frustrating to waste an afternoon to find out a faulty catalog to cause silent errors, without being able to narrow down the root cause.

**Comment by angelozerr** [comment]
@deathaxe i suggest that you create an issue per problem with a simple usecase which causes the problem.

Please note that uri resolve with catalog is done by an external librairie jar. Its not lemmix which does that so I dont know if its possible to catch those unis errors.

I wonder if vscode xml should provide a command to add xml catalog file that you can select and add it to the settings?

**Comment by lpanebr** [comment]
ok. NOW I've REALLY gotten it to work (context aware suggestions) on Windows, with multiple catalogs on Sublime and VS Code!

**Here´s what I did to get it working on Windows, after installing the LemMinx package:**
1. Instead of specifying multiple catalogs in the settings, I used just a single catalog file.
2. Instead of hand-writing the catalog myself I used multiple `<nextCatalog>` entries pointing to the DTD-libraries-provided catalog files on the same directory.
3. Corrected a problem in one of the catalog files (see note below).
4. Used only the double `\\` slash notation.
5. Enabled the `xml.validation.resolveExternalEntities` setting.
6. Installed the **LSP package**. (For Sublime only)
7. Installed Java. (required by the LSP package)

**IMPORTANT 1:**
 - The **LemMinx package** in Sublime provides only very basic validation.
 - Installing the **LSP package** is what gave Sublime the ability to provide context aware suggestions for elements, attributes and attribute values.
 - The **Exalt package** was not installed as during tests it also provided only basic validation and dumb suggestions.

**IMPORTANT 2:**
 - When I intentionally break one of the `<nextCatalog>`s files, the validation etc breaks for XML files that use that DTD but it all keeps working for XML files using the DTDs specified by the other `<nextCatalog>`s files.

---

Below are the specific packages configurations that are currently working on Windows and provide context aware suggestions for elements, attributes and attribute values, both for Sublime Text (version 4) and VS Code.

**Sublime** `LSP-lemminx.sublime-settings`
```json
{
	"settings": {
		"xml.catalogs": [
			"C:\\catalogs\\catalog.xml"
		],
		"xml.completion.autoCloseTags": true,
		"xml.validation.resolveExternalEntities": true,
	}
}
```
**VS Code** `settings.json`
```json
{
    "redhat.telemetry.enabled": false,
    "xml.catalogs": [
        "C:\\catalogs\\catalog.xml"
    ],
    "xml.completion.autoCloseTags": true,
    "xml.validation.resolveExternalEntities": true
}
```

The main `catalog.xml` has only `<nextCatalog>` entries using relative path as pointed by @deathaxe .

**Catalog file** `catalog.xml`
```xml
<?xml version="1.0"?>
<!DOCTYPE catalog PUBLIC "-//OASIS//DTD Entity Resolution XML Catalog V1.0//EN" "http://www.oasis-open.org/committees/entity/release/1.0/catalog.dtd">
<catalog prefer="public" xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
  <nextCatalog catalog="jats\\dtd\\1.1d3\\catalog-jats-v1-1d3-no-base.xml"/>
  <nextCatalog catalog="jats\\dtd\\1.1\\catalog-jats-v1-1-no-base.xml"/>
  <nextCatalog catalog="jats\\dtd\\1.0\\catalog-jats-v1.xml"/>
</catalog>
```
**DTD files used:**
 - [jats-publishing-dtd-1.0.zip](https://ftp.ncbi.nih.gov/pub/jats/publishing/1.0/jats-publishing-dtd-1.0.zip)
 - [JATS-Publishing-1-1-MathML2-DTD.zip](https://ftp.ncbi.nih.gov/pub/jats/publishing/1.1/JATS-Publishing-1-1-MathML2-DTD.zip)
 - [JATS-Publishing-1-1d3-MathML2-DTD.zip](https://ftp.ncbi.nih.gov/pub/jats/publishing/1.1d3/JATS-Publishing-1-1d3-MathML2-DTD.zip)

`catalog.xml` file and DTD libraries relative to `<nextCatalog>` files and folders. (see note below)
```
C:\\catalogs\\catalogs
├── catalog.xml
└── jats
    └── dtd
        ├── 1.0
        │   ├── catalog-jats-v1.xml    # <= problematic catalog using xml:base (see note below)
        │   ├── iso8879
        │   ├── iso9573-13
        │   ├── mathml
        │   ├── Smallsamples
        │   └── xmlchars
        ├── 1.1
        │   ├── catalog-jats-v1-1-no-base.xml
        │   ├── iso8879
        │   ├── iso9573-13
        │   ├── mathml
        │   └── xmlchars
        └── 1.1d3
            ├── catalog-jats-v1-1d3-no-base.xml
            ├── iso8879
            ├── iso9573-13
            ├── mathml
            ├── Smallsamples
            └── xmlchars
```
**Note:**
 - The `catalog-jats-v1.xml` catalog was problematic. It had a `xml:base` defined, which has to be removed.
```xml
<!-- problematic xml:base on the group definition -->
<group xml:base="file:///C:/Work/Tasks/DTDJournal/" prefer="public">

<!-- fixed group definition -->
<group prefer="public">
```

**Conclusion**
As shown above, having a single catalog that properly references other catalogs using the `<nextCatalog>` definition works as expected. So, if there really exists any bugs with multiple catalogs, I feel it must be related with either:
 - adding multiple catalog files as an array in the server json settings configuration file; or
 - using badly formed catalog files and/or path structure.

**Comment by angelozerr** [comment]
Thanks for your feedbacj @lpanebr 

Please note that you if you enable codelens, you should see someinformation about binding with DTD,XSD

Here a sample with binding with schemaLocation:

![image](https://user-images.githubusercontent.com/1932211/147917522-09e90689-c6ef-4353-ae84-1c0b650fd35c.png)

You can click on codelens to open the proper xsd.
