### ISSUE TITLE
Validation errors in references XSD files

### ISSUE THREAD

**Issue by WolfgangHG** [eclipse/lemminx#1144]
The JBoss guys often create XSD files that report validation errors in Eclipse when creating an XML file referencing this XSD.

The "Language Server" integration of Eclipse 2021-12 reports only that there are errors in the XSD files, but it does show any details.
The XML validator from WTP shows the validation errors when calling "Show Details..." in the context menu.

Here is a sample XML file:
```
<?xml version="1.0" encoding="UTF-8"?>
<jboss-web xmlns="http://www.jboss.com/xml/ns/javaee"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.jboss.com/xml/ns/javaee http://www.jboss.org/j2ee/schema/jboss-web_12_0.xsd"
           version="12.0">
	<context-root>SecurityWeb</context-root>
	<security-domain>security-sample-domain</security-domain>
	<ejb-ref>
		<ejb-ref-name>ejb/Secured</ejb-ref-name>
		<jndi-name>java:global/Security/SecurityEJB/SecuredBean!package.of.SecuredRemote</jndi-name>
	</ejb-ref>
</jboss-web>
```

This is the "Markers" view:
![Markers View](https://user-images.githubusercontent.com/138049/147885995-3bb47969-2a7f-4758-b0f4-8a51ebbebbd7.png)

**Comment by angelozerr** [comment]
Close for https://github.com/eclipse/wildwebdeveloper/issues/762

**Comment by angelozerr** [comment]
@WolfgangHG

**Comment by angelozerr** [comment]
@mickaelistria I think it's not an issue for LemMinx but I think it's for LSP4E. 

Indeed LemMinx report a Diagnostic (There are .... errors) and if LSP client supports https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#diagnosticRelatedInformation the diagnostic contains the list of detailled errors. To fix this issue:

 * LSP4E should support https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#diagnosticRelatedInformation
 * LSP4E should contribute to marker view to open list of related informations to show the detail of the error (I don't know if it's possible).
 
@WolfgangHG lease create an issue at https://github.com/eclipse/lsp4e/

**Comment by mickaelistria** [comment]
Opened https://github.com/eclipse/lsp4e/issues/37
