### ISSUE TITLE
XML validation errors of "Language Servers" are only partially visible

### ISSUE THREAD

**Issue by WolfgangHG** [eclipse/lemminx#1145]
This is from Eclipse 2021-12 (4.22): this xml snippet causes two validation errors:

```
<application xmlns="https://jakarta.ee/xml/ns/jakartaee"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/application_9.xsd">
	<invalid>
	</invalid>
</application>
```

The "Language Servers" section shows only the headers of the error message, in my sample "Attribute:" and "Invalid element name".
![Markers View](https://user-images.githubusercontent.com/138049/147885791-c7c1b971-04e3-4fcb-89a7-e7b8d9ed58e6.png)
The other two errors seem to result from the WTP XML validator.

Copying the details shows the full error:
```
Attribute:
 - version
is required in element:
 - application
```
And:
```
Invalid element name:
 - invalid

One of the following is expected:
 - application-name
 - description
 - display-name
 - icon
 - initialize-in-order
 - module
```

So, the "Markers" views should either remove the newlines or display multiline texts.

Hope this is the right place to report this issue.

**Comment by angelozerr** [comment]
I close this issue since its à lsp client issue with eclipse ide and i suppose lsp4e. See https://github.com/eclipse/wildwebdeveloper/issues/761

**Comment by WolfgangHG** [comment]
@angelozerr This issue was originally [https://github.com/eclipse/wildwebdeveloper/issues/761](https://github.com/eclipse/wildwebdeveloper/issues/761) and then moved to this project. So #761 is now closed, too. Could you reopen and move this issue to the new project?

**Comment by angelozerr** [comment]
Oh I see. @mickaelistria this issue is for lsp4e or perhaps eclipse ui marker. The problem here us that diagnostic display a readable message with line sperator and marker view shows only the first line. This problem is not linked to lemminx but to marker view.

**Comment by mickaelistria** [comment]
Could the diagnoatic be enhanced to have a more explicit 1st line then? Multiple lines can be too intrusive eg also for cases of inline diagnostics. 1st line should be a summary of the issue and not 1st line of details.

**Comment by angelozerr** [comment]
We manage this diagnostic kind to have readable error message:

![image](https://user-images.githubusercontent.com/1932211/147909378-3d8dd495-f008-49e7-9fd8-879098f2a595.png)

I don't know if we could add more content in the first line to keep this readable message.

**Comment by mickaelistria** [comment]
A summary could be `Element "invalid" is invalid here according to schema`  and then next lines can provide details.

**Comment by mickaelistria** [comment]
A summary could be `Element "invalid" is invalid here according to schema`  and then nxt lines can provide details.

**Comment by angelozerr** [comment]
@fbricon what do you think about that?

**Comment by fbricon** [comment]
+1

**Comment by angelozerr** [comment]
@JessicaJHee are you interested to work on this issue?

**Comment by JessicaJHee** [comment]
I'm interested!
