### ISSUE TITLE
Update GraalVM version used in binary verification builds

### ISSUE THREAD

**Issue by rgrunber** [eclipse/lemminx#1158]
We currently use `20.3.0` in https://github.com/eclipse/lemminx/blob/master/.github/workflows/native-image.yaml . We should look at updating to latest version and seeing what benefits result.

**Comment by fbricon** [comment]
We should try graalvm 22 on Java 17 : https://medium.com/graalvm/graalvm-22-0-is-here-c7acc82a8c2e
