### ISSUE TITLE
Endless diagnostic publishing when validation is disabled

### ISSUE THREAD

**Issue by IdanHo** [eclipse/lemminx#1175]
After updating from version 0.18.2 (As part of the vscode-xml) extension the `lemminx-linux` binary is using 100% of my cpu. (Same behaviour with 0.18.3, 0.18.4, 0.19.0). I don't have a specific xml file to point to, since it does so as soon as I open a container, without opening any XML files. I don't have debug symbols, but after attaching with GDB, these are the locations of all the threads: 
![image](https://user-images.githubusercontent.com/16208640/154034492-c2d1a392-4bf1-4fdd-90ca-3362394103ad.png)

**Comment by angelozerr** [comment]
You mean that you don't open some XML file? I have no idea why you have this problem.

@rgrunber @fbricon have you some idea?

**Comment by IdanHo** [comment]
I don't open any XML file. note that I'm running on the Remote - Containers extension connected to a CentOS 7 container. and that it happens on both Linux and WSL

**Comment by IdanHo** [comment]
Ah, after restarting the container it didn't happen, so it's likely left over from when I did open an XML file, but I created this example file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<test>
</test>
```
and as soon as I opened it started happening.

**Comment by angelozerr** [comment]
And do you benefit  with syntax validation?

**Comment by IdanHo** [comment]
I have this `"xml.validation.enabled": false` set if that's what you mean.

**Comment by angelozerr** [comment]
Could you enable xml trace https://github.com/redhat-developer/vscode-xml/blob/master/docs/Troubleshooting.md#no-support-on-xml-file and share your trace please

> I have this "xml.validation.enabled": false set if that's what you mean.

Ok but have you some XML features like completion, hover, linked editing range, etc?

**Comment by IdanHo** [comment]
> Could you enable xml trace https://github.com/redhat-developer/vscode-xml/blob/master/docs/Troubleshooting.md#no-support-on-xml-file and share your trace please

I'm just seeing this on repeat:
```
[Trace - 10:04:25 AM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///workspaces/repo/test.xml",
    "diagnostics": []
}
```

**Comment by angelozerr** [comment]
I don't understand, if you set `"xml.validation.enabled": false` you should not have 'textDocument/publishDiagnostics'.

What is your trace when the language server is started?

**Comment by angelozerr** [comment]
The impression that I have is that the language server started and (perhaps) the settings is not valid and  doesn't take care of your enabled validation settings.

The server crashes and restart again. Not sure with that but it's an idea.

**Comment by IdanHo** [comment]
Attached is the startup trace
[trace.log](https://github.com/eclipse/lemminx/files/8068105/trace.log)

**Comment by fbricon** [comment]
@IdanHo do you use a specific container? Can you install a JDK in the container and point xml.java.home to it?

**Comment by IdanHo** [comment]
> For the moment to avoid having this trouble, please set `"xml.validation.enabled": true`

Thanks!

**Comment by fbricon** [comment]
@IdanHo vscode-xml 0.19.1, which includes a fix for this issue, has been released to the VS Code Marketplace

**Comment by IdanHo** [comment]
> @IdanHo vscode-xml 0.19.1, which includes a fix for this issue, has been released to the VS Code Marketplace

That update indeed fixed the issue, thank you!
