### ISSUE TITLE
Adopt linkedEditingRanges wordPattern property

### ISSUE THREAD

**Issue by rgrunber** [eclipse/lemminx#1187]
@vrubezhny mentioned that LemMinX doesn't use the `wordPattern` property to define when the linked editing range should exit the editing mode. I believe he ran into a case where the client (Eclipse?) had a different set of word patterns and there was some unexpected behaviour. I'll let him provide more details if needed.

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#linkedEditingRanges

`wordPattern` value for some languages that may be associated with LemMinX
https://github.com/microsoft/vscode/blob/main/extensions/html/language-configuration.json#L35
https://github.com/microsoft/vscode/blob/main/extensions/xml/xml.language-configuration.json#L37

**Comment by angelozerr** [comment]
Fixed with https://github.com/eclipse/lemminx/issues/1187

Thanks @@vrubezhny !
