### ISSUE TITLE
A test file contains "private non-commercial use" clause

### ISSUE THREAD

**Issue by rlgloden** [eclipse/lemminx#1197]
The file ..\lemminx-0.20.0\org.eclipse.lemminx\src\test\resources\xml\nasa.xml contains a "private non-commercial use" clause which trips up corporate license scanners.  Was this intended?

**Comment by angelozerr** [comment]
Could you create a PR to fix this issue please?

**Comment by rgrunber** [comment]
It was introduced in https://github.com/eclipse/lemminx/issues/48 and is used mainly in the performance tests . @angelozerr , can we use another "large" file from http://aiweb.cs.washington.edu/research/projects/xmltk/xmldata/ (or http://aiweb.cs.washington.edu/research/projects/xmltk/xmldata/www/repository.html#nasa ) ?
