### ISSUE TITLE
[Question] log output 

### ISSUE THREAD

**Issue by gayanper** [eclipse/lemminx#1203]
I tried using the latest snapshot and when server is started in vscode, I can see the following log

LemMinX Server info:
 - Version : 0.21.0-SNAPSHOT
 - Java : XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 - VM Version : 11.0.14
 - Git e77594e - A test file contains "private non-commercial use" clause

What does this ` - Git e77594e - A test file contains "private non-commercial use" clause` means ?

**Comment by angelozerr** [comment]
> What does this - Git e77594e - A test file contains "private non-commercial use" clause means ?

It is the last commit that we did.

**Comment by gayanper** [comment]
Thanks @angelozerr
