### ISSUE TITLE
CodeAction for cvc-complex-type.2.4.b

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx#1218]
Given this XML file:

```xml
<web-app xmlns="http://java.sun.com/xml/ns/j2ee"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/j2ee http://java.sun.com/xml/ns/j2ee/web-app_2_4.xsd"
    version="2.4">
    <servlet></servlet>
</web-app>
```

There is an error on servlet:

![image](https://user-images.githubusercontent.com/1932211/171882785-68a42b5c-520d-4618-b2c3-b2287c0172df.png)

because servlet expects some content. It should be nice to provide a code action which generate the expected content.

**Comment by JessicaJHee** [comment]
I was taking a look at this issue to see if I can pick it up and I see that the code action for `cvc_complex_type_2_4_a` is very similar (this one is to replace the unexpected content and `cvc_complex_type_2_4_b` is to insert the expected content). When I tried out the 2_4_a code action, the error is detected properly but the diagnostic is not being sent correctly in the code action request. As a result, the code action response is empty and there is no yellow light bulb that pops up.

![image](https://user-images.githubusercontent.com/73968480/172518772-57e3bad5-a507-447f-94e6-c224e66cd9eb.png)

![image](https://user-images.githubusercontent.com/73968480/172518508-1bb8f757-9288-4f28-a996-c98789c83c8c.png)

When I try to activate other code actions (such as completing with '>'), it works fine. I also checked out the code actions tests for `cvc_complex_type_2_4_a` , which are passing as expected.  

I'm wondering if this is something on the vscode-xml side or I'm missing something (maybe a setting)?

**Comment by angelozerr** [comment]
> When I tried out the 2_4_a code action, the error is detected properly but the diagnostic is not being sent correctly in the code action request.

It works for me:

![image](https://user-images.githubusercontent.com/1932211/172543871-1fbac260-048f-4620-85f1-446cc81c1924.png)

Are you sure that you see the correct trace of codeAction? Your range of codeAction an diagnostics are not the same?

**Comment by GitMensch** [comment]
I gave this a try, works fine in general. Things I've recognized that may be considered a bug:

* the code action says "Insert all expected elements" - but it also inserts elements with `"minOccurs="0" maxOccurs="1"` --> so also optional elements (and then complains that those have an invalid data type, manually deleting those lead to a warning free xml) -> can you split this into two actions "insert all expected" and "insert all possible"?
* given a sequence of elements and missing elements at the end the code action inserts those directly at the beginning --> leading to "invalid element name" errors [if the complete complex element is empty then adding the entries via code action inserts those in the correct order] -> is it possible to insert the missing elements at the correct place?

**Comment by fbricon** [comment]
@GitMensch can you please open 2 separate issues?

**Comment by GitMensch** [comment]
Done. Again: thanks for the feature - it already is helping, it just can be even better :-)
