### ISSUE TITLE
Completion when changing a tag inserts wrong closing tag

### ISSUE THREAD

**Issue by felixfbecker** [eclipse/lemminx#122]
![2018-09-14 13 07 37](https://user-images.githubusercontent.com/10532611/45546923-348db800-b81f-11e8-923f-07917a1c2d60.gif)

The tag already has a closing tag, and I am within a starting tag, so it should insert one.

**Comment by angelozerr** [comment]
@felixfbecker I don't understand how you do that with vscode: you select a tag name and you type some content and it updates the end tag too?

Could you explain me please?

Please note that you have a rename feature which supports that.

**Comment by angelozerr** [comment]
Perhaps its' an extension that you have installed?

**Comment by angelozerr** [comment]
lsp4xml gives the capability ro rename the start/end tag element (not the whole document).

I will try to install your extension and play with it. I don't know if it's an hard task to do.

**Comment by felixfbecker** [comment]
To be entirely clear: This bug has nothing to do with the extension. It happens without the extension too.

![2018-09-14 13 40 49](https://user-images.githubusercontent.com/10532611/45548238-e29b6100-b823-11e8-8eb5-b55bcc74eb4b.gif)

**Comment by angelozerr** [comment]
I understand your problem and it should be cool to fix it, but I think it's an hard task because in your case you need to detect that `</ListItem>` is an end element which have no opened element and which be replaced with the  opened `<TableColumnItem>`.

Today the tolerant XML parser ignore the end element which have no opened element (it's the same logic than the HTML Language Server of vscode).

I keep opened this issue, but I don't know when (and if) it will be fixed. Changing the XML parser (which is a translate of HTML Language Server of vscode) scares me. Any contribution are welcome!

**Comment by felixfbecker** [comment]
Awesome. If rename works, there are definitely more important priorities like #117, https://github.com/redhat-developer/vscode-xml/issues/17

**Comment by angelozerr** [comment]
> Awesome. 

Glad it pleases you:) The only think with rename is that you have not completion.

> If rename works, there are definitely more important priorities like #117, redhat-developer/vscode-xml#17

I have an idea how to do fix it, just find time to do it:)

**Comment by angelozerr** [comment]
@felixfbecker I'm not sure, but perhaps the future settings `autoCloseTags` in https://github.com/angelozerr/lsp4xml/issues/130 could fix your problem.

**Comment by felixfbecker** [comment]
Yeah, I think I would prefer tags to not be autoclosed, since it's easy to manually close a tag by invoking autocompletion and selecting the suggestion to close the tag.

**Comment by fbricon** [comment]
Looks to me this is working as expected now (with `"editor.linkedEditing":true`:

![Feb-15-2023 13-22-47](https://user-images.githubusercontent.com/148698/219026482-9a4fc473-5caf-4bd1-8fbb-b4f21f3409fd.gif)

@felixfbecker can we close this issue?
