### ISSUE TITLE
Copy over `ModelTextDocuments#computeModelAsyncCompose` from quarkus-ls into commons package

### ISSUE THREAD

**Issue by datho7561** [eclipse/lemminx#1229]
See https://github.com/redhat-developer/quarkus-ls/pull/659/files?w=1#diff-8ffdd77369ed4ef0561d74cd65bfffd95327217e65143805720c33a137b991dd

This helper method is very helpful when implementing the `TextDocumentService` for an lsp4j-based language server, so it makes sense to include in the commons package.

**Comment by Vahalaru** [comment]
So just to be clear for this issue all I have to do is add the same code to the commons package?

**Comment by datho7561** [comment]
One part of this issue is copying over the code, another is using it in `XMLTextDocumentService` to simplify the methods where the DOMDocument is computed asynchronously, similar to how it was done in the linked PR. Thanks for asking, I should have clarified that!
