### ISSUE TITLE
XML language server shows problem marker - only if extension point editor is open

### ISSUE THREAD

**Issue by jukzi** [eclipse/lemminx#1235]
error `src-resolve.4.2: Error resolving component 'serviceFactory'. It was detected that 'serviceFactory' is in namespace 'http://www.w3.org/2001/XMLSchema', 
but components from this namespace are not referenceable from schema document 'file:///C:/Users/jkubitz/2022-05-09/git/eclipse.platform.ui/bundles/org.eclipse.ui/schema/services.exsd'. 
If this is the incorrect namespace, perhaps the prefix of 'serviceFactory' needs to be changed. 
If this is the correct namespace, then an appropriate 'import' tag should be added to 'file:///C:/Users/jkubitz/2022-05-09/git/eclipse.platform.ui/bundles/org.eclipse.ui/schema/services.exsd'.
	services.exsd	/org.eclipse.ui/schema	line 31	Language Servers`
the file in question is this:
https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/bundles/org.eclipse.ui/schema/services.exsd#L31

1. why an error is shown at all - everything works just fine?
2. why is the error only shown when  extension point editor is open?

Is any of  this a lemmix issue?
PDE claims that is not an issue inside the file (generated by PDE). see https://github.com/eclipse-pde/eclipse.pde/issues/175

**Comment by mickaelistria** [comment]
@angelozerr what do you think of this issue?

**Comment by angelozerr** [comment]
I need some investigation why WTP doesn't report this error and why LemMinx report it.

**Comment by mickaelistria** [comment]
Note that WTP is not used by PDE editor, it's a different XML editor. So maybe WTP would told the same error if it were used and some schema provided by PDE may be incorrect.

**Comment by angelozerr** [comment]
WTP has exactly the same problem:

![image](https://user-images.githubusercontent.com/1932211/175283731-086676d1-4eaa-4f25-8100-d937777301af.png)

As validation is done by xerces I fear that it will hard to fix it.

**Comment by jukzi** [comment]
https://github.com/eclipse-pde/eclipse.pde/issues/175#issuecomment-1311633626
