### ISSUE TITLE
Support `xml.format.enforceQuoteStyle` setting with experimental formatter

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx#1239]
See https://github.com/redhat-developer/vscode-xml/blob/master/docs/Formatting.md#xmlformatenforcequotestyle

**Comment by JessicaJHee** [comment]
Yes looks interesting!

**Comment by angelozerr** [comment]
@JessicaJHee for the test I have copy/pasted the test from the old formatter in https://github.com/eclipse/lemminx/blob/master/org.eclipse.lemminx/src/test/java/org/eclipse/lemminx/services/format/experimental/XMLFormatterQuoteStyleTest.java

All tests are disabled https://github.com/eclipse/lemminx/blob/a099dc2953cc6d87babec769d108b6c8274b26ae/org.eclipse.lemminx/src/test/java/org/eclipse/lemminx/services/format/experimental/XMLFormatterQuoteStyleTest.java#L31

The main idea is to 

 * remove those @Disabled annotation once you will support corectly quote.
 * the last line of your test must be `assertFormat(expected, expected, settings);` it means that the format of expected content should not changed and no text edit should be generate. You can see that for other tests like https://github.com/eclipse/lemminx/blob/a099dc2953cc6d87babec769d108b6c8274b26ae/org.eclipse.lemminx/src/test/java/org/eclipse/lemminx/services/format/experimental/XMLFormatterExperimentalIndentTest.java#L36
