### ISSUE TITLE
Support `xml.format.joinCDATALines` setting with experimental formatter

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx#1241]
See https://github.com/redhat-developer/vscode-xml/blob/master/docs/Formatting.md#xmlformatjoincdatalines

**Comment by rgrunber** [comment]
Maybe this can also fix https://github.com/redhat-developer/vscode-xml/issues/719 ?

**Comment by JessicaJHee** [comment]
I'm interested in working on this!
