### ISSUE TITLE
Support `xml.format.spaceBeforeEmptyCloseTag` setting with experimental formatter

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx#1245]
See https://github.com/redhat-developer/vscode-xml/blob/master/docs/Formatting.md#xmlformatspacebeforeemptyclosetag

**Comment by angelozerr** [comment]
@JessicaJHee are you interested to work on this issue?

**Comment by JessicaJHee** [comment]
Yes I'm interested!
