### ISSUE TITLE
CodeAction for cvc-complex-type.2.4.b: "insert all expected" vs. "insert all possible"

### ISSUE THREAD

**Issue by GitMensch** [eclipse/lemminx#1255]
the code action says "Insert all expected elements" - but it also inserts elements with `"minOccurs="0" maxOccurs="1"` --> so also optional elements (and then complains that those have an invalid data type, manually deleting those lead to a warning free xml) -> can you split this into two actions "insert all expected" and "insert all possible"?

_Originally posted by @GitMensch in https://github.com/eclipse/lemminx/issues/1218#issuecomment-1190078320_

**Comment by angelozerr** [comment]
Could you give us a very simple  ml and xsd for this issue. We could use them for tests.

Thanks!

**Comment by GitMensch** [comment]
Not complete but possibly enough:

```xsd
	<xs:element name="cmplx">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="a" minOccurs="1" maxOccurs="1"/>
				<xs:element name="b" minOccurs="0" maxOccurs="1"/>
				<xs:element name="c" minOccurs="0" maxOccurs="1"/>
				<xs:element name="d" minOccurs="1" maxOccurs="1"/>
				<xs:element name="e" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
```

and

```xsd
	<cmplx>
	</cmplx>
```

**Comment by JessicaJHee** [comment]
I'm interested in this issue!
