### ISSUE TITLE
The XML language server crashed 5 times in the last 10 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by lautnerxing** [eclipse/lemminx#1263]
![image](https://user-images.githubusercontent.com/51226709/181202569-dd36e684-d876-415c-8398-144a1aa00ae2.png)

**Comment by angelozerr** [comment]
Could you please create an issue on vscode-xml and give us more information with traces like explained here https://github.com/redhat-developer/vscode-xml/blob/main/docs/Troubleshooting.md#troubleshooting please.

I close the issue since the problem comes from the vscode-xml.
