### ISSUE TITLE
Invalid "schemaLocation" is not reported if "Enable schema validation = In valid schema"

### ISSUE THREAD

**Issue by WolfgangHG** [eclipse/lemminx#1272]
This is a followup to #1143 : this xml file has an invalid schema location URL:

```
<?xml version="1.0" encoding="UTF-8"?>
<jboss-web xmlns="http://www.jboss.com/xml/ns/javaee"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.jboss.com/xml/ns/javaee http://some.invalid.host.com"
           version="12.1">
</jboss-web>
```

The invalid schema url is only reported if the setting "Enable schema based validation" is set to "Always".
![schemabasedvalidation](https://user-images.githubusercontent.com/138049/184533667-6a2d3b18-37b6-4a98-ba9d-78e2f2b3eab8.png)

This is the error:
![validationerror](https://user-images.githubusercontent.com/138049/184533760-eca6711d-c351-4396-947b-0f46cf24a2d9.png)

But the default "In valid schema" does not report this error.

I consider this a bug: if a schema location is specified, the user should be informed in case this location is invalid. Otherwise, the user could think that the xml file is valid as no errors are shown. And schema completion will not work, but the user will not see the reason.

In #1143, @angelozerr also suggested to change the default value for this setting to "Always".

**Comment by angelozerr** [comment]
This issue is for wwd. In vscode xml we have already this default value.

**Comment by angelozerr** [comment]
I close the issue. Please create the issue in wwd.
