### ISSUE TITLE
Error range for src-annotation `src-annotation`

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx#1276]
Given this XSD file:

```xml
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="root-element">
	<xs:annotation>
		<xs:appInfo>
			
		</xs:appInfo>
	</xs:annotation>	
	</xs:element>
</xs:schema>
```

![image](https://user-images.githubusercontent.com/1932211/184900535-4a8910d1-6c3f-405f-a8c2-342f1c78b286.png)
``
`xs:appInfo` report an error because it should be `xs:appinfo`, the error range should higlight the `xs:appInfo`. We could provide too code action with similar values and REPLACE with `xs:appinfo`.

See https://github.com/eclipse-pde/eclipse.pde/issues/294

**Comment by raj99195** [comment]
you should write  app:info instead of app:Info.

**Comment by datho7561** [comment]
Clsoed by #1581
