### ISSUE TITLE
Lemminx not able to fetch my dtd file

### ISSUE THREAD

**Issue by UtkarshVerma** [eclipse/lemminx#1287]
I am trying to use Lemminx to validate my fontconfig XML file. However, it keeps throwing the error that it cannot find the DTD file.
`fonts.dtd` is a systemwide file on Linux machines and is located in `/usr/share/xml/fontconfig/fonts.dtd`. Is there any way I can tell Lemminx to recognize the fontconfig urn?

![image](https://user-images.githubusercontent.com/31820255/187850271-54feeae0-1aee-44fa-a6b5-864ba848f87d.png)

Could you please let me know how I can fix this?

**Comment by fbricon** [comment]
You need to define a catalog that maps `urn:fontconfig:fonts.dtd` to `/usr/share/xml/fontconfig/fonts.dtd`.
So, first create a catalog.xml on your machine, containing:
```xml
<!DOCTYPE catalog
    PUBLIC "-//OASIS//DTD Entity Resolution XML Catalog V1.0//EN"
    "http://www.oasis-open.org/committees/entity/release/1.0/catalog.dtd">
<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog" prefer="public">
    <system systemId="urn:fontconfig:fonts.dtd" uri="/usr/share/xml/fontconfig/fonts.dtd" />
</catalog>
```
You then need to pass the following setting to lemminx:
```json
"xml.catalogs": [ "/path/to/catalog.xml"]
```

**Comment by UtkarshVerma** [comment]
Thank you for the help. Is there also a way I could do this without creating the catalog file?

**Comment by angelozerr** [comment]
I fear that there is no solution without catalog. You can see a comment which is speaking about that for fontconfig https://github.com/freedesktop/fontconfig/commit/9c46ef4aac87c42d013d0e7380b6aeb03e1a9949

**Comment by angelozerr** [comment]
I suggest that you create an issue in https://github.com/neovim/nvim-lspconfig to provide this catalog settings.

**Comment by UtkarshVerma** [comment]
Thank you for your help regarding this. I will create an issue there.

**Comment by UtkarshVerma** [comment]
```
lspconfig.lemminx.setup({
    on_attach = on_attach,
    settings = {
        xml = {
            catalogs = { "/etc/xml/catalog" }
        }
    }
})
```

Doing this worked for me. Had to append fontconfig DTD to the catalog though.

**Comment by angelozerr** [comment]
Glad you fixed yoir issues. 

Thnank you for your feedback and I hope you will continue to enjoy with lemminx.
