### ISSUE TITLE
POM XML formatter incorrectly adds newlines before CDATA sections

### ISSUE THREAD

**Issue by garretwilson** [eclipse/lemminx#1360]
(This was originally filed as eclipse-m2e/m2e-core#1015, but I was told I need to file it with Eclipse Wild Web Developer; but after filing it again as eclipse/wildwebdeveloper#941 I was told I need to file it with LemMinX, whatever that is. So here we are.)

Using Eclipse 2022-09, I can add a CDATA section inside a Maven POM (`pom.xml`) property definition like this:

```xml
<properties>
    <test.cdata><![CDATA[<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties>
	<entry key="foo">bar</entry>
</properties>]]></test.cdata>
</properties>
```

The purpose is obvious: I don't want to XML-encode all the XML delimiters in the value.

However when I format the file using `Ctrl+Shift+F`, Eclipse adds newlines and indents before and after the CDATA section:

```xml
<properties>
    <test.cdata>
      <![CDATA[<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties>
	<entry key="foo">bar</entry>
</properties>]]>
    </test.cdata>
<properties>
```

This corrupts the data! The whole point of using a CDATA section is that I wanted the _exact_ content specified in a property. Now extra whitespace has been added in the value of the property. (It would have been worse to format inside the CDATA section, but this is still not good.)

I would guess the problem is that the formatting algorithm is treating CDATA sections as if they were XML DOM elements. That is, I understand that if I have this XML:

```xml
<foo><bar>…</bar></foo>
```

Then the XML formatter should format it to:

```xml
<foo>
  <bar>…</bar>
</foo>
```

However CDATA sections are not elements! Their purpose is merely to indicate whether content needs escaping or should be interpreted literally. _They do not create a new element nesting context!!!_ They must be left along entirely; no newlines, whitespace, or anything else should be added, neither inside the CDATA section, before the CDATA section, nor after the CDATA section.

**Comment by fbricon** [comment]
LemMinX's new experimental formatter already supports this use case. You can check it in VS Code with the [XML extension](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml), after setting `"xml.format.experimental": true` in the [settings](https://github.com/redhat-developer/vscode-xml/blob/main/docs/Formatting.md#xmlformatexperimental).

WWD should be updated to expose that setting. So https://github.com/eclipse/wildwebdeveloper/issues/941 still stands

**Comment by mickaelistria** [comment]
we'll just wait for the formatter to be fixed/enabled by default.
