### ISSUE TITLE
xml.format.preserveEmptyContent behaves erratically

### ISSUE THREAD

**Issue by enxio** [eclipse/lemminx#1366]
Given the following content
```xml
<a>
   <b>1234 1234 1234 1234 1234 1234 1234 1234 1234 1234 1234 12341234          1234</b>
</a>
```
formatting the document with `xml.format.preserveEmptyContent` set to `true`, the excess spaces are not removed. This is either a bug in the documentation, where "empty" is explained and shown or in the function. If set to `false`, the format works as expected.

**Comment by angelozerr** [comment]
@enxio we would like to remove this settings in the experimental formatter, please see issue https://github.com/eclipse/lemminx/issues/1346

Please comment in this issue if you  are OK or not to remove this settings by explaining why you need this setting.

**Comment by angelozerr** [comment]
I close this issue since #1346 will remove this setting
