### ISSUE TITLE
xml.format.joinContentLines joins all content on to single line

### ISSUE THREAD

**Issue by JessicaJHee** [eclipse/lemminx#1380]
![Peek 2022-11-24 10-48](https://user-images.githubusercontent.com/73968480/203824500-05b1bb34-3bbc-4222-97ea-1de2ed487b58.gif)

With the experimental formatter: 

Since max line width disabled by default, when either the `xml.format.joinContentLines`, `xml.format.joinCommentLines`, or `xml.format.joinCDATALines` is applied, all content will be joined on to one line. 

One possible solution to this is to set a default max line width for just these 3 settings, which can be over written with the actual max line width setting if an user chooses to set it.

**Comment by angelozerr** [comment]
Perhaps we should set à default value again for max line width?

**Comment by JessicaJHee** [comment]
I think that could be a good idea. In oxygen the default is set to 100, but we could set it to 80 like before.

**Comment by JessicaJHee** [comment]
Closing this issue because the `xml.format.maxLineWidth` setting now has a default value of 100 and this is no longer a problem.
