### ISSUE TITLE
Surround with tags fails when there is no root element

### ISSUE THREAD

**Issue by datho7561** [eclipse/lemminx#1395]
eg.

```xml
<?xml version="1.0" encoding="UTF-8"?>
|
```

Trigger surround with tags at the `|`. (You can also reproduce the issue in an empty file).

In the logs, I get:
```
[Trace - 9:48:52 a.m.] Received response 'workspace/executeCommand - (77)' in 5ms. Request failed: undefined (-32001).
Error data: {}


[Error - 9:48:52 a.m.] Request workspace/executeCommand failed.
  Message: 
  Code: -32001 
[object Object]
```

**Comment by datho7561** [comment]
It also seems to fail if the cursor is outside of the root element

**Comment by angelozerr** [comment]
I think this issue is when you are using file association, no?

If you create a file without file association (without grammar linked), have you this issue?

**Comment by datho7561** [comment]
I'll double check...

**Comment by datho7561** [comment]
Yes, you are right. It only happens when the xml is associated with a grammar through a file association.
