### ISSUE TITLE
Completion, definition, highlight support for attributes which have references with settings

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx#1427]
I noticed that there are a lof XML which declare some references between attribute like :

 * docbook with `xref@linkend` -> `*/@id` :

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book PUBLIC "-//OASIS//DTD DocBook XML V4.4//EN" "http://www.docbook.org/xml/4.4/docbookx.dtd">
<book>
    <chapter id="chapter-1">

        <xref linkend="chapter-1" />

    </chapter>

    <chapter id="chapter-2">

    </chapter>
</book>
```

 * TEI with `corresp` and `resp` attributes `@corresp` -> `@xml:id`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_lite.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>  
    <fileDesc>
      <titleStmt>
        <title>Title</title>
      </titleStmt>
      <publicationStmt>
        <p>Publication information</p>  
      </publicationStmt>
      <sourceDesc>
        <p>Information about the source</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body xml:id="body-id">
      <p xml:id="p-id" >Some text here.</p>
      <anchor corresp="#body-id"></anchor>
    </body>
  </text>
</TEI>
```

Docbook uses ID, IDREF for xlink, so we could use this info (on the future), but this issue is to declare those links with settings

 * for docbook, we could declare link like this:

```json
  "xml.references": [
    {
      "pattern": "**/*.xml",
      "expressions": [
        {
          "from": "xref/@linkend",
          "to": "@id"
        }
      ]
    }
  ]
```
 * for TEI, we could declare link like this:

```json
"xml.references": [
    {
      "pattern": "**/*.xml",
      "expressions": [
        {
          "prefix": "#",
          "from": "@resp",
          "to": "persName/@xml:id"
        },
        {
          "prefix": "#",
          "from": "@corresp",
          "to": "@xml:id"
        }
      ]
    }
  ]
```

 * for Pretext, we could declare link like this:

```json
"xml.references": [
		{
			"pattern": "**/*.ptx",
			"expressions": [
				{
					"from": "xref/@ref",
					"to": "@xml:id"
				}
			]
		}
	]
```

This settings provides the capability to declare references betwwen attributes and will support (without coding something):

 * completion for referenced attributes
 * definition for a referenced attribute
 * highlight to hoghlight the refrenced attribute

**Comment by angelozerr** [comment]
@oscarlevin I think this issue could interest you, here a demo with PreText with the settings explained below:

![PreTextReferencesDemo](https://user-images.githubusercontent.com/1932211/208875640-6fce2759-7913-4dda-9543-c69bf007c548.gif)

**Comment by angelozerr** [comment]
@JulieGiovacchini I see you could be interested with this issue. See https://github.com/eclipse/lemminx/pull/1428#issuecomment-1361102350

**Comment by JulieGiovacchini** [comment]
> @JulieGiovacchini I see you could be interested with this issue. See [#1428 (comment)](https://github.com/eclipse/lemminx/pull/1428#issuecomment-1361102350)

I have seen, I will definitely use it! Thank you !

**Comment by angelozerr** [comment]
@JulieGiovacchini if you wish to play with xml.references, please read https://github.com/redhat-developer/vscode-xml/blob/main/docs/Features/XMLReferencesFeatures.md#xml-references-features and more specially for you, https://github.com/redhat-developer/vscode-xml/blob/main/docs/Features/XMLReferencesFeatures.md#prefix
