### ISSUE TITLE
Exception while using `textDocument/documentColor` with binary

### ISSUE THREAD

**Issue by datho7561** [eclipse/lemminx#1436]
When I try to use the new colors feature with the binary version of lemminx in VS Code, I get:

`Message: Unable to create instance of class org.eclipse.lsp4j.ColorPresentationParams. Registering an InstanceCreator or a TypeAdapter for this type, or adding a no-args constructor may fix this problem.`

I think that all that's needed to fix it is to update `reflect-config.json` in order to register the no-args constructor for reflection.

**Comment by angelozerr** [comment]
My bad I forget to test with binary. Is there any chance that you create a pr please?

**Comment by datho7561** [comment]
Okay, I can put it together
