### ISSUE TITLE
Wrap long lines

### ISSUE THREAD

**Issue by oliviercailloux** [eclipse/lemminx#1439]
The behavior described [here](https://bugs.eclipse.org/bugs/show_bug.cgi?id=501252) seems to happen to POM formatting, namely, the first line is not wrapped. Instead, it displays an overly long line, and even merges the lines if they are manually wrapped.

I believe it should wrap the line at some reasonable length, by default (and I suppose this could be configurable with some line length parameter).

**Comment by angelozerr** [comment]
@JessicaJHee could you look at this issue please.
