### ISSUE TITLE
Potential regression in XML autoformatter for pom.xml editor view - Newlines get stripped

### ISSUE THREAD

**Issue by Jotschi** [eclipse/lemminx#1454]
I have recently updated my Eclipse IDE and noticed that manually added newlines will be removed when invoking the autoformatter in the pom.xml tab of the Maven POM Editor.

The regular XML editor does not show this behavior. I would use the XML editor but I really like the option to jump/follow to different pom.xml files using the individual dependencies.

Please let me know if you think this issue may be related to the m2e project. I'm happy to open an issue there instead.

I'm using: Eclipse IDE for Java Developers

Version: 2022-12 (4.26.0) Build id: 20221201-1913

Steps to reproduce:

* Open pom.xml 
* Switch to pom.xml editor tab
* Add newlines in between tags
* Hit CTRL+SHIFT+F
* Observe that newlines will be removed

**Comment by fbricon** [comment]
This is an issue of [WWD](https://github.com/eclipse/wildwebdeveloper/issues), that integrates Lemminx but only exposes a subset of its preferences  in 2022-12. 
It appears newer WWD now provides a more complete [set of prefs](https://github.com/eclipse/wildwebdeveloper/blob/571032537442c4ded2408c9162317eeafc74823a/org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/messages.properties#LL43C15-L43C15), so you can try installing a [recent snapshot](https://github.com/eclipse/wildwebdeveloper#as-extension-into-an-existing-eclipse-ide-installation).

**Comment by Jotschi** [comment]
Thanks for the quick reply. An update of WWD resolved the issue.
