### ISSUE TITLE
conform spec: shutdown response does not conform to language-server spec

### ISSUE THREAD

**Issue by KMikeeU** [eclipse/lemminx#1508]
From what I've found, the language-server spec specifies, that the response to a shutdown request should have a result of `null` (see [here](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#shutdown)), however it seems that in `XMLLanguageServer.java` a `new Object()` is returned instead.

I wanted to create a pull request, but since that involved giving you my full name and contact information, I thought I would just add the suggested patch here, as it is very small.

```diff
From 5af36dcc72ae4e4eb03a86909dab28eed118e795 Mon Sep 17 00:00:00 2001
From: Michael <20937441+KMikeeU@users.noreply.github.com>
Date: Thu, 6 Apr 2023 23:47:02 +0200
Subject: [PATCH 1/1] spec: shutdown returns null

---
 .../src/main/java/org/eclipse/lemminx/XMLLanguageServer.java    | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/XMLLanguageServer.java b/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/XMLLanguageServer.java
index baa11711..506138cf 100644
--- a/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/XMLLanguageServer.java
+++ b/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/XMLLanguageServer.java
@@ -238,7 +238,7 @@ public class XMLLanguageServer implements ProcessLanguageServer, XMLLanguageServ
 		if (capabilityManager.getClientCapabilities().shouldLanguageServerExitOnShutdown()) {
 			delayer.schedule(() -> exit(0), 1, TimeUnit.SECONDS);
 		}
-		return computeAsync(cc -> new Object());
+		return computeAsync(cc -> null);
 	}

 	@Override
--
2.40.0

```

**Comment by datho7561** [comment]
Does this affect any clients that you've used? I tested it with VS Code and neovim, and it seems to work there.

I'll make the fix; we can also get rid of the `computeAsync`, since it makes no sense to cancel the shutdown request. This might save a few bytes of RAM during shutdown :D

**Comment by KMikeeU** [comment]
> Does this affect any clients

Yes I was planning to integrate with https://github.com/helix-editor/helix, the internal LSP just panics

Thank you!
