### ISSUE TITLE
Bind XML with no grammar constraints to XSD / DTD

### ISSUE THREAD

**Issue by fbricon** [eclipse/lemminx#151]
IntelliJ IDEA has this command to automatically generate an XSD schema from an XML file:

![generate-schema](https://user-images.githubusercontent.com/148698/46209686-7d07a400-c2fc-11e8-9608-c5461a9f1877.gif)

Such command would take at least 2 parameters:
- source file URI
- target XSD file URI (optional, would default to source name without extension + ".xsd")

I'd give that issue a very low priority, until other people vote for it.

**Comment by bmix** [comment]
Ideally, this would need more than just one XML instance document to get a better understanding of structure.
