### ISSUE TITLE
Configurable path to cache directory (or using XDG dirs)

### ISSUE THREAD

**Issue by msva** [eclipse/lemminx#1514]
Hi there!

I've found that lemminx uses `~/.lemminx/cache` directory for cache, and I can't find any way to reconfigure it.
I'd like to keep home directory as clean as possible, and it will be good to set up lemminx to use another cache directory (for example, ~/.local/state/lemminx/cache` as some other langservers does, but I'd like to be able to set it up to either use `$XDG_CACHE_HOME` environment variable (if exists), or to set custom cache directory path)

is it somehow possible? or, if not, could you please implement that?

**Comment by fbricon** [comment]
You need to configure the path of the "xml.server.workingDir" preference.
- eg. in neovim: https://neovim.discourse.group/t/lemminx-configuration/3895
- in vscode-xml: https://github.com/redhat-developer/vscode-xml/blob/main/docs/Preferences.md#server-cache-path

**Comment by msva** [comment]
Thanks a lot!
