### ISSUE TITLE
Cache refreshing

### ISSUE THREAD

**Issue by msva** [eclipse/lemminx#1515]
Hi there!
Is it possible to, say, setup caching timeout, or something like that?
Or is it any way to ask lemminx to re-cache resources?

(excluding manual removing files from the cache directory)

**Comment by angelozerr** [comment]
Lemminx provides two command to revalidate files and evict cache.

We use it in vscode xml https://github.com/redhat-developer/vscode-xml/blob/main/docs/Commands.md#revalidate-current-xml-file

**Comment by msva** [comment]
Thanks!

Although, I'm not sure how to implement the same with neovim, but anyway, thanks a lot.
I'll continue digging.
