### ISSUE TITLE
PrepareRename/Rename Server Capabilities doesn't work with non dynamic registration

### ISSUE THREAD

**Issue by vrubezhny** [eclipse/lemminx#1551]
LSP4E's[ LSPRenameProcessor.isPrepareRenameProvider](https://github.com/eclipse/lsp4e/blob/master/org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/rename/LSPRenameProcessor.java#L164)  expects to get `Either.forRight(Either<Boolean, RenameOptions>)` for Rename capability to initiate  the `prepareRename`/`rename` requests sending to the server, otherwise, even if  `(Boolean)TRUE` is returned by `serverCapabilities.getRenameProvider()` the rename operation fails. 

Lemminx declares that it has `Rename` capability, but does not provide `RenameOptions`, which prevents `prepareRename` requests to be sent to server.

**Comment by angelozerr** [comment]
Is not an issue with LSP4E since it is working with vscode

**Comment by angelozerr** [comment]
@vrubezhny after seeing your PR I undertsand your fix and it make senses. The problem comes from when LSP client cannot support dynamic rename registration.

I will merge your PR but I think you should fix LS4PE too support dynamic rename registration.
