### ISSUE TITLE
Last updates breaks pretext-tools in codespaces

### ISSUE THREAD

**Issue by oscarlevin** [eclipse/lemminx#1557]
It appears that the 0.26.0 update changed something so that when running VS Code in a github codespace, something is broken.  I only noticed this because my pretext-tools extension (which requires XML) didn't work after the update, but it appears that the XML extension itself isn't working.  For example, if I go to the command pallet, I get only the XML: Open XML Documentation command, not the other expected ones (that do show up in 0.25.0).

**Comment by angelozerr** [comment]
@oscarlevin do you use binary on linux?

If it that I think it is the same problem than https://github.com/redhat-developer/vscode-xml/issues/916

//cc @rgrunber

**Comment by vrubezhny** [comment]
In vscode itself, following your example, I get these commands:

![Screenshot from 2023-07-12 16-44-29](https://github.com/eclipse/lemminx/assets/620781/d3e2d818-fe6a-4d56-b29c-88dc8895ed48)

And pretty the same command list I have in GitHub codespace with vscode-xml 0.2.6 installed:

![Screenshot from 2023-07-12 16-54-15](https://github.com/eclipse/lemminx/assets/620781/103aca28-d805-466e-b6d2-5650ed357a7c)

Am I messing anything?

**Comment by vrubezhny** [comment]
@angelozerr @rgrunber Do you know if `vscode-xml` running on GitHub CodeSpaces uses any binaries?

**Comment by rgrunber** [comment]
If there's no Java in the container then it would use the binary. If the underlying container environment uses a version of GLIBC < 2.34, then this would be https://github.com/redhat-developer/vscode-xml/issues/916.

**Comment by vrubezhny** [comment]
In my case, the vscode-xml extension running on GitHub CodeSpaces has `XML> Server: Prefer Binary` option NOT selected:

![Screenshot from 2023-07-12 17-40-03](https://github.com/eclipse/lemminx/assets/620781/608c8581-28ef-4874-a43b-303ab91a63d1)

**Comment by angelozerr** [comment]
I suspect that the problem of @oscarlevin is with binary since 0.26.0 doesn't contain major changes.

**Comment by angelozerr** [comment]
> In my case, the vscode-xml extension running on GitHub CodeSpaces has XML> Server: Prefer Binary option NOT selected:

What about if you select it?

@oscarlevin could you deselect it in your side to check if it is working for you?

**Comment by oscarlevin** [comment]
Thanks all for the quick response.  I won't be able to experiment for a bit.  When I get a chance I'll see if this is the issue.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rgrunber** [comment]
Just to be clear, at https://github.com/redhat-developer/vscode-xml/blob/f99df7e859c61256ebd05382f106fc0c5042d1e1/src/server/serverStarter.ts#L28 we do launch the binary even if the choice is not selected. The binary covers the case of not detecting Java on the system but wanting to give a seamless experience.

https://github.com/redhat-developer/vscode-xml/blob/f99df7e859c61256ebd05382f106fc0c5042d1e1/src/server/serverStarter.ts#L28 .

@oscarlevin , If possible, you could try the following vsix : https://github.com/rgrunber/vscode-xml/releases/download/0.26.0/vscode-xml-linux-x64-0.26.0-284.vsix . I mentioned it in https://github.com/redhat-developer/vscode-xml/issues/916#issuecomment-1631782966 . It is basically 0.26.0 but the Linux binary was built on an older version of Ubuntu for better support of older Linux distros.

**Comment by vrubezhny** [comment]
@angelozerr Yes. I can confirm the issue. Turning on the `XML> Server: Prefer Binary` makes all the commands but the "Open XML Documentation" to disappear  . So it looks like a binary  problem.

**Comment by vrubezhny** [comment]
@oscarlevin @rgrunber For me the vscode-xml extension works fine when installed from https://github.com/rgrunber/vscode-xml/releases/download/0.26.0/vscode-xml-linux-x64-0.26.0-284.vsix :

![Screenshot from 2023-07-12 19-24-43](https://github.com/eclipse/lemminx/assets/620781/3910cf09-0e9b-401b-a2af-b06874f7f921)

**Comment by oscarlevin** [comment]
I  can finally confirm that this is fixed and working for me.  Thanks all for your work.
