### ISSUE TITLE
Implement itemDefaults for CompletionList 

### ISSUE THREAD

**Issue by JessicaJHee** [eclipse/lemminx#1561]
In lemminx maven, there are completions that returns a lot of items in the result. To improve the performance, implement itemDefaults at the end of completion here: 

https://github.com/eclipse/lemminx/blob/2b0fe29f52c111be3d5c1dccdf9d08340c63be31/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/services/XMLCompletions.java#L290

The idea is to get the most common `editRange` between all completion items and set that as in itemDefaults.

**Comment by angelozerr** [comment]
I wanted to test this feature inEclipse IDE but it seems it is not supported https://github.com/eclipse/lsp4e/issues/741
