### ISSUE TITLE
Cannot download lemminx dependency 0.20.0 - 4.0.3 

### ISSUE THREAD

**Issue by pablocabrera85** [eclipse/lemminx#1574]
When trying to resolve lemminx dependencies as part of our build, we are getting the following error:

https://repo.eclipse.org/content/repositories/lemminx-releases/org/eclipse/lemminx/org.eclipse.lemminx/0.20.0/org.eclipse.lemminx-0.20.0.pom

<img width="1249" alt="image" src="https://github.com/eclipse/lemminx/assets/3269977/47390f83-9d2f-414d-bf9c-6ca4413a3edd">

**Comment by fbricon** [comment]
Looks like an Eclipse Foundation Infra issue, I'll ping them

**Comment by SantiSuarezMS** [comment]
@fbricon were you able to reach them? Did you get an ETA?

**Comment by fbricon** [comment]
@SantiSuarezMS it was supposed to be fixed 2h ago. But it's still failing: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3557#note_1197917

**Comment by fbricon** [comment]
Repo is back online

**Comment by pablocabrera85** [comment]
Hi @fbricon this is broken again. Should I create a new ticket or reopen this?

**Comment by pablocabrera85** [comment]
I guess they are taking a look into it based on the status here: 

https://www.eclipsestatus.io/

**Comment by fbricon** [comment]
seems to be back online
