### ISSUE TITLE
No document links in catalog's <system uri="..." />

### ISSUE THREAD

**Issue by fbricon** [eclipse/lemminx#220]
While testing the examples from https://raw.githubusercontent.com/microclimate-devops/xml-language-server/master/client-vscode/xml-client/readme-resources/examples.zip, when editing catalog/catalog.xml, I don't get an hyperlink from uri="invoice.xsd" to the actual file.

```xml
<?xml version="1.0"?>
    <catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
    <system systemId="http://invoice.xsd" uri="invoice.xsd"/>
</catalog> 
```

**Comment by angelozerr** [comment]
It's because it's not implemented:) It should cool to implement that with https://github.com/angelozerr/lsp4xml/issues/168

**Comment by fbricon** [comment]
It's fine. Not a priority for now. Let's focus on https://github.com/angelozerr/lsp4xml/milestone/3

**Comment by angelozerr** [comment]
@fbricon once #168 will be implemented, it will open a lot of features, that we will able to manage with declaration mean with easy mean.

For instance, with just a declaration like

```
from="/system/@uri"
toFile="**/**.xsd"
```
we could benefit with:

 * hyperlink
 * completion
 * validation
