### ISSUE TITLE
Fault tolerance needs improvement

### ISSUE THREAD

**Issue by NikolasKomonen** [eclipse/lemminx#305]
In a case like:

`<a bb="asd" "aaa"> </a>`

the value `"aaa"` will be lost since it hits an unknown state.

In similar situations these unknown states need to atleast remember the content or else it will be lost.

**Comment by angelozerr** [comment]
This issue is about formatting, experimental formatter https://github.com/redhat-developer/vscode-xml/blob/master/docs/Formatting.md#xmlformatexperimental fix this issue.
