### ISSUE TITLE
Synced editing of opening/closing element tags

### ISSUE THREAD

**Issue by bmix** [eclipse/lemminx#362]
Would it be possible to automatically mirror any changes to any of the two connected elements to the other? (I tried making a screen recording, but boy, after 1h of installing screen recorder tools (Windows), configuring them, using legacy software, just to realize, that editing them gives me an unusable AVI, I gave up on that :-) )

So, if I rename the opening tag, the changes automatically get applied to the closing tag, without needing to use the rename dialog?

Thanks. (I am using the VSCode release)

**Comment by angelozerr** [comment]
I agree with you but i fear its not possible with lsp. We should create an
issue in lsp github spec project to manage this rename preview feature

**Comment by bmix** [comment]
Now, that you say it and if I think about it, this is actually something, that belongs to the editor side and not to a server. It's just some string/syntax work and does not have any semantics and so does not require any deeper evaluation.

**Comment by angelozerr** [comment]
This issue is now supporter with LSP linked editing range.
