### ISSUE TITLE
Completion for locally declared entity

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx#520]
Completion for declared entity

Given this XML file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE article [
  <!ENTITY mdash "&#x2014;">
]>
<root>
  |
</root>
```

It should be cool to have completion on [ to show `mdash  `entity. When it will be inserted, it must generate `&mdash ;`

**Comment by ph777** [comment]
Any plans to support this? It would be great help.

**Comment by angelozerr** [comment]
@ph777  I'm working on this issue, but it will work for only local entities. Is it a feature which could help you or not? I think you wish to have completion on external DTD but I wanted just to know if local completion entity could be helpful for you.

**Comment by ph777** [comment]
Thanks for asking. We use both local and external entities. We would
appretiate if both worked. However, improvement on local entities is also a
valuable improvement ;-)

Is it hard to also do external entities?

Dne pá 24. dub 2020 21:23 uživatel Angelo <notifications@github.com> napsal:

**Comment by angelozerr** [comment]
>  We would appretiate if both worked. However, improvement on local entities is also a
valuable improvement ;-)

Ok thanks for your feedback.

> Is it hard to also do external entities?

I don't know, I need to investigate Xerces support for that, see https://github.com/eclipse/lemminx/issues/660
