### ISSUE TITLE
Improve XML formatter (option to have Tags in the same line)

### ISSUE THREAD

**Issue by rwx-777** [eclipse/lemminx#594]
Hello, again we spoke earlier already [here](https://github.com/redhat-developer/vscode-xml/issues/200). As requested here we will be listing some examples by Screenshots and the use case of our improvements.

When viewing a larger XML-File with your Tool it always puts some Tags in a New Line.
We have edited this to not be the case anymore.
It would be very appreciated if we could have the option of using this.

Here are some before and after screenshots of an XML-File.

Before our Improvements:

![test-vorher](https://user-images.githubusercontent.com/26744048/68936460-e6fe3980-079a-11ea-82b6-6b5b77be4b93.png)

After our Improvements:

![test-nachher](https://user-images.githubusercontent.com/26744048/68936503-009f8100-079b-11ea-89c7-0a92a5a8adff.png)

Here is the link to the Github Repo where we have stored our changed version:
[https://github.com/rwx-777/lsp4xml-AtSec-Edition](url)

Use Case:
- Tags can appear in the same line

Thank you for your time and we are looking forward to what is to come. 

Best regards,

Joshua

**Comment by angelozerr** [comment]
Before implementing this feature, I would like to clarify the feature about formatting. I have the impression that is a `xml:space` support formatting that it should be done.

Here 3 links why I suppose it's about xml:space:

 * http://www.xmlplease.com/xml/xmlspace/
 * http://tei-l.970651.n3.nabble.com/oXygen-and-the-quot-Format-and-Indent-quot-function-tt2346233.html#a2346236
 * https://www.oxygenxml.com/forum/topic10259.html#p28680

@rwx-777 could you explain us how to you configure this format settings in Oxygen?

**Comment by enxio** [comment]
Hi Angelo, I work with the OP. I am not sure that it's about xml:space what Oxygen did different. Oxygen (at least the version I was using) had three settings:
- A list of elements where space would be preserved
- A list of elements where space was handled "defalt" i.e. normalized.
- A list of elements with mixed content - no linebreaks are inserted between adjacent elements
Oxygen's formatter tried to inline the tags more or less automatically, and almost always produced something that was easy to read. Basically what our formatting hack does.

**Comment by angelozerr** [comment]
> Oxygen's formatter tried to inline the tags more or less automatically, and almost always produced something that was easy to read. Basically what our formatting hack does.

Thanks for your feedback @enxio I would like to understand the Oxygen rule to try to format automatically when it's possible.

Takes your sample, my question is do you need to customize something with Oxygen to avoid having nolinebreak? If no, it seems that you are linked to a DTD, so I suppose Oxygen uses DTD information to know if it must generate line break or not.

**Comment by enxio** [comment]
To be honest, I never fully understood how Oxygen did it or what the actual algorithm was. In the example, Oxygen formats in a similar fashion. I didn't have to configure anything, basically. I did configure the elements to preserve the space, that's all, the rest was default.

Attached is a screenshot from the relevant configuration options for Oxygen 14 as an Eclipse plugin.

<img width="492" alt="Screenshot 2019-11-19 at 12 02 38" src="https://user-images.githubusercontent.com/31342498/69141350-e0d2ca80-0ac4-11ea-8670-e39b0b5dd609.png">

**Comment by enxio** [comment]
Here's how Oxygen format an XML File without a DTD.

<img width="1008" alt="Screenshot 2019-11-19 at 12 19 19" src="https://user-images.githubusercontent.com/31342498/69142329-dc0f1600-0ac6-11ea-903c-70effc25086a.png">

**Comment by angelozerr** [comment]
@enxio if I understand your explanation, you have not done some configuration with para element to avoid line break after para element? 

I would like to understand more with some usecases:

Given this XML file:

```xml
<root><para>ab cd ef <b>DDD</b>  </para></root>
```

LSP4XML formatting result is (same with WTP XML):

```xml
<root>
	<para>
		ab cd ef
		<b>DDD</b>
	</para>
</root>
```

 * http://www.editix.com/ -> XML formater online https://www.webtoolkitonline.com/xml-formatter.html:

```xml
<root>
    <para>ab cd ef 
        <b>DDD</b>
    </para>
</root>
```

@enxio  what about Oxygen?

**Comment by enxio** [comment]
It keeps the `b`inline.
```xml
<root>
   <child>ab cd ef <b>DDD</b>
   </child>
</root>
```

**Comment by angelozerr** [comment]
> And Oxygen keeps the binline.

Ok thanks, I wornder why in your case the </para> is not in the new line.

And if you format in Oxygen this XML?

```xml
<root>
   <child>ab cd ef <b>DDD</b> ggggg
   </child>
</root>
```

do you have the formatted result:

```xml
<root>
   <child>ab cd ef <b>DDD</b> ggggg</child>
</root>
```

**Comment by enxio** [comment]
Yes, that's the result I get.

**Comment by angelozerr** [comment]
Thanks @enxio I found very interesting information about Oxygen formatting at https://www.oxygenxml.com/doc/versions/21.1/ug-editor/topics/format-and-indent-xml-x-modes2.html#format-and-indent-xml__how_determines_when_whitespace_is_significant

We could start to implement some important features of formatting options.

**Comment by enxio** [comment]
Very good. If there is use for the changes we already made, please let me know how and if that can be the done.

**Comment by angelozerr** [comment]
@NikolasKomonen if you wish work on this issue, I think it should be good to play with Oxygen (the main problem is that it's a paid product) and collect a lot of use cases (that we could use for our junit tests).

In other words before implementing anything,please share in this issue the use cases and what options you want to provide. Thank's!

**Comment by enxio** [comment]
@NikolasKomonen I do have an Oxygen Installation available, so if there is anything I can help you with, please let me know.

**Comment by angelozerr** [comment]
@enxio if you can share with us usescases, it should be very cool. For each usecase we should have

 * Oxygen settings 
 * XML to format
 * Formatted XML

Thanks for your help.

**Comment by enxio** [comment]
@angelozerr so you basically want to specify these changes by use cases? OK, I'll try one:

Setting Indent inline elements, bool

True:

<img width="963" alt="Screenshot 2019-11-26 at 14 53 54" src="https://user-images.githubusercontent.com/31342498/69639358-a6d16d80-105c-11ea-8e21-63412414913d.png">

False:

<img width="958" alt="Screenshot 2019-11-26 at 14 54 49" src="https://user-images.githubusercontent.com/31342498/69639400-ba7cd400-105c-11ea-990c-6fec19a8108f.png">

Also: https://www.oxygenxml.com/doc/versions/21.1/ug-editor/topics/preferences-editor-format-xml.html

**Comment by angelozerr** [comment]
@enxio please describe your usecase as text and not as image. We will able to use your usecase for our Junit. Thanks!

**Comment by enxio** [comment]
Setting Indent inline elements, bool

True:

```xml
<para>All DocBook V5.0 elements are in the namespace <uri>http://docbook.org/ns/docbook</uri>. <acronym>XML <alt>Extensible Markup
                  Language</alt>
            </acronym> namespaces are used to distinguish between different element sets. In the last few years, almost all new XML grammars
            have used their own namespace. It is easy to create compound documents that contain elements from different XML vocabularies.
            DocBook V5.0 is following this design rule. Using namespaces in your documents is very easy. Consider this simple article marked
            up in DocBook V4.5:</para>
```

False:

```xml
<para>All DocBook V5.0 elements are in the namespace <uri>http://docbook.org/ns/docbook</uri>. <acronym>XML <alt>Extensible Markup
            Language</alt> </acronym> namespaces are used to distinguish between different element sets. In the last few years, almost all new
            XML grammars have used their own namespace. It is easy to create compound documents that contain elements from different XML
            vocabularies. DocBook V5.0 is following this design rule. Using namespaces in your documents is very easy. Consider this simple
            article marked up in DocBook V4.5:</para>
```

related documentation: https://www.oxygenxml.com/doc/versions/21.1/ug-editor/topics/preferences-editor-format-xml.html

**Comment by enxio** [comment]
@angelozerr is there something you would to address/implement first? Are the examples above helpful?

**Comment by angelozerr** [comment]
@enxio more we will have usecases, more it will be more easy to find the settings and have a robust formatting feature because we will use your usecase in our JUnit.

**Comment by enxio** [comment]
```xml
<para>All DocBook V5.0 elements are in the namespace <uri>http://docbook.org/ns/docbook</uri>. <acronym>XML <alt>Extensible Markup
            Language</alt></acronym> namespaces are used to distinguish between different element sets. In the last few years, almost all new
            XML grammars have used their own namespace. It is easy to create compound documents that contain elements from different XML
            vocabularies. DocBook V5.0 is 
            
            
            <emphasis>following</emphasis> this 
            <emphasis>design</emphasis>/<emphasis>rule</emphasis>. 
            
            Using
            namespaces in your documents is very easy. Consider this simple article marked up in DocBook V4.5:</para>
```
with default settings becomes
```xml
 <para>All DocBook V5.0 elements are in the namespace <uri>http://docbook.org/ns/docbook</uri>. <acronym>XML <alt>Extensible Markup
            Language</alt></acronym> namespaces are used to distinguish between different element sets. In the last few years, almost all new
            XML grammars have used their own namespace. It is easy to create compound documents that contain elements from different XML
            vocabularies. DocBook V5.0 is <emphasis>following</emphasis> this <emphasis>design</emphasis>/<emphasis>rule</emphasis>. Using
            namespaces in your documents is very easy. Consider this simple article marked up in DocBook V4.5:</para>
```

**Comment by enxio** [comment]
With para in Oxygen's Mixed Content

```xml
<para>All DocBook V5.0 elements are in the namespace <uri>http://docbook.org/ns/docbook</uri>. <acronym>XML <alt>Extensible Markup
            Language</alt></acronym> namespaces are used to distinguish between different element sets. In the last few years, almost all new
            XML grammars have used their own namespace. It is easy to create compound documents that contain elements from different XML
            vocabularies. DocBook V5.0 is 
            
            <emphasis>following</emphasis> 
            
            <emphasis>this</emphasis>
            
            <emphasis>design</emphasis>/<emphasis>rule</emphasis>. 
            
Using
            namespaces in your documents is very easy. Consider this simple article marked up in DocBook V4.5:</para>
```
becomes
```xml
<para>All DocBook V5.0 elements are in the namespace <uri>http://docbook.org/ns/docbook</uri>. <acronym>XML <alt>Extensible Markup
            Language</alt></acronym> namespaces are used to distinguish between different element sets. In the last few years, almost all new
            XML grammars have used their own namespace. It is easy to create compound documents that contain elements from different XML
            vocabularies. DocBook V5.0 is <emphasis>following</emphasis> <emphasis>this</emphasis>
            <emphasis>design</emphasis>/<emphasis>rule</emphasis>. Using namespaces in your documents is very easy. Consider this simple
            article marked up in DocBook V4.5:</para>
```

**Comment by enxio** [comment]
With para in Oxygen's Default Space
```xml
         <para>All DocBook V5.0 elements are in the namespace <uri>http://docbook.org/ns/docbook</uri>. <acronym>XML <alt>Extensible Markup
            Language</alt></acronym> namespaces are used to distinguish between different element sets. In the last few years, almost all new
            XML grammars have used their own namespace. It is easy to create compound documents that contain elements from different XML
            vocabularies. DocBook V5.0 is 
            
            <emphasis>following</emphasis> 
            
            <emphasis>this</emphasis>
            
            <emphasis>design</emphasis>/<emphasis>rule</emphasis>.        
Using
            namespaces in your documents is very easy. Consider this simple article marked up in DocBook V4.5:</para>
```
becomes
```xml
<para>All DocBook V5.0 elements are in the namespace <uri>http://docbook.org/ns/docbook</uri>. <acronym>XML <alt>Extensible Markup
            Language</alt></acronym> namespaces are used to distinguish between different element sets. In the last few years, almost all new
            XML grammars have used their own namespace. It is easy to create compound documents that contain elements from different XML
            vocabularies. DocBook V5.0 is <emphasis>following</emphasis> <emphasis>this</emphasis>
            <emphasis>design</emphasis>/<emphasis>rule</emphasis>. Using namespaces in your documents is very easy. Consider this simple
            article marked up in DocBook V4.5:</para>
```

**Comment by enxio** [comment]
Preserve empty lines:

```xml
 <title>Finally in a namespace</title>

         <para>All DocBook V5.0 elements are in the namespace <uri>http://docbook.org/ns/docbook</uri>. <acronym>XML <alt>Extensible Markup
            Language</alt></acronym> namespaces are used to distinguish between different element sets. In the last few years, almost all new
            XML grammars have used their own namespace. It is easy to create compound documents that contain elements from different XML
            vocabularies. DocBook V5.0 is <emphasis>following</emphasis> 
            
            
            
            <emphasis>this</emphasis>
            <emphasis>design</emphasis>/<emphasis>rule</emphasis>. Using namespaces in your documents is very easy. Consider this simple
            article marked up in DocBook V4.5:</para>
```
becomes

True:
```xml
<title>Finally in a namespace</title>

         <para>All DocBook V5.0 elements are in the namespace <uri>http://docbook.org/ns/docbook</uri>. <acronym>XML <alt>Extensible Markup
            Language</alt></acronym> namespaces are used to distinguish between different element sets. In the last few years, almost all new
            XML grammars have used their own namespace. It is easy to create compound documents that contain elements from different XML
            vocabularies. DocBook V5.0 is <emphasis>following</emphasis> <emphasis>this</emphasis>
            <emphasis>design</emphasis>/<emphasis>rule</emphasis>. Using namespaces in your documents is very easy. Consider this simple
            article marked up in DocBook V4.5:</para>
```
False:
```xml
<title>Finally in a namespace</title>
         <para>All DocBook V5.0 elements are in the namespace <uri>http://docbook.org/ns/docbook</uri>. <acronym>XML <alt>Extensible Markup
            Language</alt></acronym> namespaces are used to distinguish between different element sets. In the last few years, almost all new
            XML grammars have used their own namespace. It is easy to create compound documents that contain elements from different XML
            vocabularies. DocBook V5.0 is <emphasis>following</emphasis> <emphasis>this</emphasis>
            <emphasis>design</emphasis>/<emphasis>rule</emphasis>. Using namespaces in your documents is very easy. Consider this simple
            article marked up in DocBook V4.5:</para>
```

**Comment by enxio** [comment]
Break line before attribute's name:

False:
```xml
<article version="5.0" xml:lang="en" xmlns="http://docbook.org/ns/docbook" xmlns:xl="http://www.w3.org/1999/xlink">
```
True:
```xml
<article
   version="5.0"
   xml:lang="en"
   xmlns="http://docbook.org/ns/docbook"
   xmlns:xl="http://www.w3.org/1999/xlink">
```

**Comment by enxio** [comment]
With code in the list of elements to preserve space:
```xml
         <para>All DocBook V5.0 elements are in the namespace <uri>http://docbook.org/ns/docbook</uri>. <acronym>XML <alt>Extensible Markup
            Language</alt></acronym> namespaces are used to distinguish between different element sets. In the last few years, almost all new
            XML grammars have used their own namespace. It is easy to create compound documents that contain elements from different XML
            vocabularies. DocBook V5.0 is <emphasis>following</emphasis> <emphasis>this</emphasis>
            <emphasis>design</emphasis>/<emphasis>rule</emphasis>. Using namespaces in your documents is very easy. Consider this simple
            article marked up in DocBook V4.5: <code>
               foo();
               bar();   
            </code>
```
becomes
```xml
<para>All DocBook V5.0 elements are in the namespace <uri>http://docbook.org/ns/docbook</uri>. <acronym>XML <alt>Extensible Markup
            Language</alt></acronym> namespaces are used to distinguish between different element sets. In the last few years, almost all new
            XML grammars have used their own namespace. It is easy to create compound documents that contain elements from different XML
            vocabularies. DocBook V5.0 is <emphasis>following</emphasis> <emphasis>this</emphasis>
            <emphasis>design</emphasis>/<emphasis>rule</emphasis>. Using namespaces in your documents is very easy. Consider this simple
            article marked up in DocBook V4.5: <code>
               foo();
               bar();   
            </code> </para>
```
If code is not to be space preserved:
```xml
<para>All DocBook V5.0 elements are in the namespace <uri>http://docbook.org/ns/docbook</uri>. <acronym>XML <alt>Extensible Markup
            Language</alt></acronym> namespaces are used to distinguish between different element sets. In the last few years, almost all new
            XML grammars have used their own namespace. It is easy to create compound documents that contain elements from different XML
            vocabularies. DocBook V5.0 is <emphasis>following</emphasis> <emphasis>this</emphasis>
            <emphasis>design</emphasis>/<emphasis>rule</emphasis>. Using namespaces in your documents is very easy. Consider this simple
            article marked up in DocBook V4.5: <code> foo(); bar(); </code> </para>
```

**Comment by enxio** [comment]
Is this something you can work with already?

**Comment by angelozerr** [comment]
> Is this something you can work with already?

Thanks so much for your usecases! @NikolasKomonen do you think you could work on this issue by using usecases ?

**Comment by angelozerr** [comment]
@enxio @rwx-777 I will try to understand option from Oxygen and do something.

**Comment by enxio** [comment]
@angelozerr thank a lot! I'll try my best to be helpful.

**Comment by angelozerr** [comment]
This issue should be fixed by the experimental formatter https://github.com/redhat-developer/vscode-xml/blob/master/docs/Formatting.md#xmlformatexperimental

**Comment by enxio** [comment]
Very good work! Thanks a lot!!!!

**Comment by angelozerr** [comment]
> Very good work! Thanks a lot!!!!

Glad you like it, but we need to improve again our experimental formatter to support the settings from the current formatter. I created issues for that.
