### ISSUE TITLE
Add onTagText to IHoverParticipant (or extend IHoverParticipant)

### ISSUE THREAD

**Issue by AObuchow** [eclipse/lemminx#609]
For the LemMinX/lsp4xml Maven extension, I would like to add support for hover request when hovering over text within a tag. Currently, [IHoverParticipant](https://github.com/angelozerr/lsp4xml/blob/68d929216d7d459cca1309f0a23eaad09ca825ca/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/services/extensions/IHoverParticipant.java) only declares hovers for `onTag`, `onAttributeName` and `onAttributeValue`. 
Since the interface is already in use, perhaps a `IHoverParticipantExtension` should be added, which would declare `onTagText`. This function would only be called when the child of a node contains only text content (and not another node/tag).

This is required for https://github.com/AObuchow/lsp4xml-extensions-maven/issues/30 as well as other use cases. For a demo of the hover we are trying to implement, [see this GIF.](https://photos.app.goo.gl/Myy3yBwgnUG4aJVU6)

**Comment by angelozerr** [comment]
Totally agree with you. Any pr are welcome!

**Comment by angelozerr** [comment]
> Since the interface is already in use, perhaps a IHoverParticipantExtension should be added, which would declare onTagText.

No please not do that, the participant API are not frozen for the moment since we are not in 1.0.0 version

**Comment by AObuchow** [comment]
> > Since the interface is already in use, perhaps a IHoverParticipantExtension should be added, which would declare onTagText.
> 
> No please not do that, the participant API are not frozen for the moment since we are not in 1.0.0 version

Okay sounds good! 
Will the 1.0.0 version occur with the first, new release of LemMinX? (Wanted to know how much time I have to get this in before the API freeze)

**Comment by angelozerr** [comment]
> Will the 1.0.0 version occur with the first,

Not for the moment, any PR are welcome!

**Comment by angelozerr** [comment]
@AObuchow have you an idea when you could provide a PR?

**Comment by AObuchow** [comment]
@angelozerr my next task is to work on this PR. As I haven't started yet, I'm not sure of the complexity of this task. Once I get started I'll have a better idea, and will hopefully be able to give a time estimate.

**Comment by angelozerr** [comment]
> @angelozerr my next task is to work on this PR. 

Great!

It should be very cool if we could have this feature in the next release. But if it's not possible we will do that in an another release. Don't hesitate to ask me if you need some help.

**Comment by AObuchow** [comment]
> It should be very cool if we could have this feature in the next release. But if it's not possible we will do that in an another release. Don't hesitate to ask me if you need some help.

Sounds good, it was actually a lot easier than I anticipated :) I'm optimistic the feature will be ready for the next release.
