### ISSUE TITLE
In Maven <configuration>, all known XML elements from schema are suggested as completion

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lemminx#612]
In Maven <configuration>, all known XML elements from schema are suggested as completion.
This is typically not desired as the Maven extension can provide higher quality proposals here and the extra items are useless and generate noise reducing the usability.

**Comment by angelozerr** [comment]
This behaviour is because of use of `processContents`  in XML Schema of configuration:

```xml
<xs:element minOccurs="0" name="configuration">

        <xs:complexType>
          <xs:sequence>
            <xs:any minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
          </xs:sequence>
        </xs:complexType>
</xs:element>
```
> This is typically not desired as the Maven extension can provide higher quality proposals here and the extra items are useless and generate noise reducing the usability.

If I understand your need, you want to manage completion for configuration in your maven lsp4xml extension? If it that I agree and we should give the capability to override the default behaviour of XML Schema completion.

**Comment by mickaelistria** [comment]
> If I understand your need, you want to manage completion for configuration in your maven lsp4xml extension? 

Yes

> If it that I agree and we should give the capability to override the default behaviour of XML Schema completion.

It seems to me that `processContents="skip"` and the absence of target namespace means that the XML Schema completion/validation is to be totally ignored in that block (as opposed to `strict` or `lax` values).
It seems to me that the schema is correct and there are already enough info in it to decide of not adding completion items, without overriding anything.

**Comment by angelozerr** [comment]
>It seems to me that processContents="skip" and the absence of target namespace means that the XML Schema completion/validation is to be totally ignored in that block (as opposed to strict or lax values).

For validation yes (you can add any XML content), but for completion we decide to provide something for this issue
https://github.com/redhat-developer/vscode-xml/issues/177#issuecomment-520449004

In other words, some user want to have this completion behaviour, but I agree with you, if you write an extension and you wish to override this behaviour, it's annoying. So we need to give the capability for an extension to override this default XML Schema behaviour.

**Comment by mickaelistria** [comment]
> For validation yes (you can add any XML content), but for completion we decide to provide something for this issue redhat-developer/vscode-xml#177 (comment)

You mentioned on that comment that user should use `lax` and not `skip`, so aren't we agreeing here?
IMO, validation and completion are similar: if schema says it can validate, it means it can complete; if it says it skips validation, then it should skip complete.

> In other words, some user want to have this completion behaviour

Why aren't they using `lax` then?

> So we need to give the capability for an extension to override this default XML Schema behaviour.

It seems to me that the schema has everything necessary, the LS shouldn't facilitate the work with bad schemas if as a consequence it reduces the quality of the work with good schemas (like Maven one).

**Comment by angelozerr** [comment]
After playing with WTP XML editor, it seems it shows root elements like project:

![image](https://user-images.githubusercontent.com/1932211/76215931-00c30100-6210-11ea-8695-f372a00ae617.png)

**Comment by mickaelistria** [comment]
WTP XML isn't always a good reference ;) But if LemMinX is tweaked so that it would only show the "project" element as additional items in configuration block, it would already be nice and probably enough.

**Comment by angelozerr** [comment]
> WTP XML isn't always a good reference ;) 

To be honnest with you, I have not a strong opinion about the proper behavior about `skip`.

@fbricon what do you think about that?

**Comment by fbricon** [comment]
let's compare with other editors first

**Comment by angelozerr** [comment]
It seems oxygen works like WTP XML Editor:

![image](https://user-images.githubusercontent.com/1932211/76234884-9a97a780-622a-11ea-8f65-c7458bd76e2f.png)
