### ISSUE TITLE
"subproject" for Maven extension

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lemminx#615]
We'd like to contribute our Maven extension for LemMinX to an Eclipse-friendly place.
We've considered Maven project, but this will require CQ everytime we want to use a newer build.
We've considered m2e, but the project fails at having a growing and diverse code-contributors community, and ultimately we think our extension will suffer from the same issue if it's too close from m2e.
And we've considered LemMinX but couldn't find a but...

So we think having this extension being a component of LemMinX is what would make it evolve best.
Concretely, it could be a eclipse/lemminx.maven Git repo and nothing more.

What do you think?

**Comment by fbricon** [comment]
If the maven extension is meant to be shipped with m2e, then it needs to be with m2e. Or else you'd have a cyclic dependency m2e <- lemminx <- m2e
If not, then it could be a lemminx subproject.

**Comment by mickaelistria** [comment]
the Maven extension is meant to be shipped as a plain jar (like LemMinX itself). It doesn't have dependencies on m2e, nor won't have any.
Then m2e will consume LemMinX and this extension and Wild Web Developer to build a pom editor.
I don't think there is a cyclic dependency.

**Comment by akurtakov** [comment]
The maven extension is supposed to be usable by anyone opening pom.xml file with LemMinX - eclipse, vscode...whatever.

**Comment by angelozerr** [comment]
> The maven extension is supposed to be usable by anyone opening pom.xml file with LemMinX - eclipse, vscode...whatever.

Indeed and it exists a vscode extension which consumes maven extension in https://github.com/angelozerr/vscode-xml-maven I'm waiting for that you stabilize your work to update the JAR.

**Comment by mickaelistria** [comment]
So there we are: Lemminx had its first Eclipse.org release, so we upgraded the Maven extension to use it, and we are now ready to submit it to Eclipse.org.
How should we proceed? Should the Maven extension be a subfolder of existing Lemminx repo, or an alternative repo in the Lemminx project...? Or a separate project?

**Comment by fbricon** [comment]
Either a sub-project or at least a separate git repo

**Comment by mickaelistria** [comment]
If we can start with a separate Git repo, that'd be great!

**Comment by mickaelistria** [comment]
Do we all agree a dedicated Git repo under Lemminx project is a good thing? If yes, how can we make it happen? I guess it's mostly submitting CQ and then asking webmaster for a repo migration?

**Comment by akurtakov** [comment]
Hey guys, can we proceed on this one?

**Comment by mickaelistria** [comment]
The contribution CQ is pre-approved, @AObuchow commiter nomination is ongoing, and I checked with @waynebeaton and only org.jsoup 1.9.2 requires a CQ. We're close to resolution.

**Comment by mickaelistria** [comment]
Code is moved, CI build is being set up, I think we can close the ticket and the remaining step will be tracked under the lemminx-maven Git repo.
