### ISSUE TITLE
Find definition for locally declared entity 

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx#625]
Find definition for declared local entity .

Given this XML file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE article [
  <!ENTITY mdash "&#x2014;">
]>
<root>
  &mdash;&mdash;
</root>
```

Ctrl+click on `&mdash;`should find definition of `mdash `

![LocalEntityDefinitionDemo](https://user-images.githubusercontent.com/1932211/82033349-e2a8cf80-969c-11ea-9acf-b01ce1ef3f74.gif)

**Comment by angelozerr** [comment]
@ph777 I think you will be interested with this feature. It works only for local entity.

**Comment by ph777** [comment]
Thx, looks promising.

Pavel

Dne pá 15. kvě 2020 11:15 uživatel Angelo <notifications@github.com> napsal:
