### ISSUE TITLE
Hover should ignore xsd:appinfo

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx#630]
Hover for XML Schema documentation should ignore xsd:appinfo.

Download  XML Schema https://github.com/redhat-developer/vscode-xml/files/4029276/AUTOSAR_00048.zip

Write xml like this:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<AUTOSAR xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://autosar.org/schema/r4.0" xsi:schemaLocation="http://autosar.org/schema/r4.0 AUTOSAR_00048.xsd">
  <AR-PACKAGES>
```

Hover the AR-PACKAGES and you will see this hover:

![image](https://user-images.githubusercontent.com/1932211/79038893-5b6bc600-7bdd-11ea-8280-3d8eef61056b.png)

`atpSplitable` should not appear (it's the behavior of WTP XML Editor)

**Comment by fbricon** [comment]
So maybe only display the xsd:appinfo if there's no XSD documentation
