### ISSUE TITLE
Formatting with "xml.format.emptyElements": "expand" chokes on malformed XML

### ISSUE THREAD

**Issue by fbricon** [eclipse/lemminx#650]
Set  "xml.format.emptyElements": "expand" in the preferences, then
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<a>
    <a>
        <a/></a>
    </a>
</a>
```
after formatting, becomes:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<a>
    <a>
        <a></a>
    </a>
</a></a>
```

![Apr-22-2020 11-33-10](https://user-images.githubusercontent.com/148698/79966156-4ae50680-848d-11ea-8fb2-b20d7faaebfa.gif)

**Comment by angelozerr** [comment]
@fbricon I don't see a real bug here, what do you want to have as format result?

**Comment by angelozerr** [comment]
This issue is fixed with experimental formatter. @JessicaJHee wrote a test for this usecase.
