### ISSUE TITLE
Is it possible to disable some extension?

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lemminx#657]
For our tests with pom.xml, I'd like to isolate things a bit more and disable the XSD extensions so we only see the features that come from the specific extension.
Is there a way to achieve that?

**Comment by angelozerr** [comment]
> Is there a way to achieve that?

No today because we don't need that.

Is your test is done with XMLLanguageService ? If you do that we could set `registerExtension` as protected and for your test you could extends XMLLanguageService  with MyXMLLanguageService 
and  override the `registerExtension` to ignore the XSD extensions.

**Comment by mickaelistria** [comment]
Thanks, that's very helpful and good enough for our use-case.

**Comment by angelozerr** [comment]
registerExtension cannot be overrided, so why you close this issue?

**Comment by mickaelistria** [comment]
Ah sorry, I misunderstood. Actually, we're not using the XMLLanguageServer but we do instantiate an XMLLanguageServer and set a connection through it. So we cannot customize much here (the xmlLanguageService field in XMLLanguageServer is private so it cannot be overridden).

**Comment by angelozerr** [comment]
>  Actually, we're not using the XMLLanguageServer but we do instantiate an XMLLanguageServer and set a connection through it.

I think it should be better to use directly XMLLanguageService which will speed up the test. We do that and it works pretty well.

**Comment by mickaelistria** [comment]
Thanks for the advice, we'll probably do that.
In the meantime, I think the XMLLanguageService should offer the registerExtension/unregisterExtension methods as public. so one could use `xmlLanguageServer.getXMLLanguageService().unregisterExtension(undesiredExtension))`.

This is likely to be very convenient for IDE intergrations if we want to support dynamic plugin/enablement/disablemetn of extensions.

**Comment by angelozerr** [comment]
Yes sure, please do a PR.

**Comment by mickaelistria** [comment]
I tried your suggestion of using XMLLanguageService, so this is not needed any more.
Thanks a lot!
