### ISSUE TITLE
Hover for referenced entities

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx#663]
Given this XML file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE article [
  <!ENTITY mdash "&#x2014;">
]>
<root>
  &mdash;
</root>
```

when `&mdash;` is hovered, we should see the same information than entities completion:

![image](https://user-images.githubusercontent.com/1932211/80498082-99057880-896b-11ea-8f9b-c29fe038b4ed.png)

It should work for external entities too (entities declared in a DTD ).

**Comment by angelozerr** [comment]
@mickaelistria @AObuchow @Seiphon I need to change the `IHoverParticipant `API for `onText` because for entities hover, the range is not the full text range, so I need to return the entity range (ex : abcd&a|mp;efg -> I must return range of &amp; and not the full range text). 

I'm afraid that I must change the API. To be consistent with other on* method, I think I will return Hover too instead of String.

**Comment by AObuchow** [comment]
@angelozerr this should be okay, just @mention me in the PR to change the API so I can get a heads up as to how things will need to be adjusted in LemMinX-Maven.

**Comment by angelozerr** [comment]
> @angelozerr this should be okay

Thanks for your answer and your understand. I will ping you as soon as my work will be merged (I hope this week).

**Comment by mickaelistria** [comment]
FWIW, we'll stick to current release of LemMinX for 2020-06 anyway (both in Wild Web Developer and m2e), after 2020-06, we can adopt newer snapshots and APIs in those projects.
