### ISSUE TITLE
Fix error range for `SemicolonRequiredInReference`

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx#664]
Given this XML file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE article [
  <!ENTITY mdash "&#x2014;">
]>
<root>
  &mdash
</root>
```

`&mdash` should be ends with `;` and Xerces report the error as `SemicolonRequiredInReference`. We should adjust error range to highlight `&mdash`

**Comment by fbricon** [comment]
@datho7561 can you look at this one next please?
