### ISSUE TITLE
Code action for `SemicolonRequiredInReference` 

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx#665]
Given this XML file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE article [
  <!ENTITY mdash "&#x2014;">
]>
<root>
  &mdash
</root>
```
There is an error for `&mdash` because it misses `;`  we should provide a code action to fix that to insert at the end of  `&mdash`  the missing `;`

**Comment by yashTEF** [comment]
Hi @angelozerr,
I am a little new to language servers so this could help me in getting started.
For debugging lemMinx I'm thinking about creating a test plugin and declaring generic editors, contentTypes etc as extension points and implementing StreamConnectionProvider for the client, as mentioned [here](https://www.eclipse.org/community/eclipse_newsletter/2017/may/article3.php).
Is this the right way or there is a simpler way to debug the server?

**Comment by angelozerr** [comment]
I dont know Who you want to debug lemminx but if you want to debug it with www eclipse ide you can create the launch. Please read https://github.com/eclipse/wildwebdeveloper/issues/266#issuecomment-535386454 (replace lsp4xml with lemminx)

**Comment by yashTEF** [comment]
@datho7561 Sure, I am inspecting the code base and trying to understand it, However I might need some help.
