### ISSUE TITLE
creating lot of workingCopy files

### ISSUE THREAD

**Issue by gayanper** [eclipse/lemminx#668]
When working with the Language server some time huge number of files are created as below.

![image](https://user-images.githubusercontent.com/7471994/80607826-404ee200-8a36-11ea-9bad-f58955e10083.png)

**Comment by angelozerr** [comment]
@gayanper it's a problem from https://github.com/eclipse/lemminx-maven please create an issue on this project.

Thanks!

**Comment by gayanper** [comment]
This happens to any xml file @angelozerr. I tried on plan xml file as well.

**Comment by angelozerr** [comment]
I suppose problem comes from https://github.com/eclipse/lemminx-maven/blob/ff015785cb5270c104aaf2fafb10df89d058cb10/lemminx-maven/src/main/java/org/eclipse/lemminx/maven/MavenProjectCache.java#L173

**Comment by AObuchow** [comment]
This is indeed a Lemminx-Maven problem :) Just wanted to confirm
