### ISSUE TITLE
Lone quote inside tag leads to catastrophic formatting

### ISSUE THREAD

**Issue by fbricon** [eclipse/lemminx#679]
When formatting a document containing a single quote inside a tag, everything right to the quote disappears:

![May-06-2020 00-23-37](https://user-images.githubusercontent.com/148698/81122038-5a099100-8f30-11ea-889f-943e348cb97d.gif)

**Comment by fbricon** [comment]
Might be a duplicate of #675, not sure

**Comment by fbricon** [comment]
Tentative target fix for 0.12.0

**Comment by angelozerr** [comment]
This issue should be fixed by the experimental formatter https://github.com/redhat-developer/vscode-xml/blob/master/docs/Formatting.md#xmlformatexperimental
