### ISSUE TITLE
Quote style not being enforced when formatting DTD

### ISSUE THREAD

**Issue by xorye** [eclipse/lemminx#686]
Example:
```
<!DOCTYPE note SYSTEM "note.dtd">
<test a="hi"></test>
```

To reproduce the issue:
1. Set `xml.format.enforceQuoteStyle` to `preferred`
2. Set `xml.preferences.quoteStyle` to `single`
3. Format the document above

Expected behaviour: 
`"note.dtd"` in line 1 should turn into `'note.dtd'`
`"hi"` in line 2 should turn into `'hi'`

Actual behaviour:
Only `"hi"` in line 2 should turns into `'hi'`:
![image](https://user-images.githubusercontent.com/20326645/81573014-ef15eb00-9371-11ea-8404-1e413ac4e5e4.png)

**Comment by fbricon** [comment]
Fixed with #724
