### ISSUE TITLE
Provide formatted XML snippets

### ISSUE THREAD

**Issue by xorye** [eclipse/lemminx#694]
As mentioned in https://github.com/eclipse/lemminx/pull/680#issuecomment-626901845, it would be nice if the snippets provided by lemminx would respect the formatting settings.

For example, if `XMLFormattingOptions#isSplitAttributes()` is false, then the noNamespaceSchemaLocation snippet: https://github.com/eclipse/lemminx/blob/25cf8e4862532b512dcc67303eb5fce7607a7003/org.eclipse.lemminx/src/main/resources/org/eclipse/lemminx/services/snippets/new-xml-snippets.json#L83-L95

should insert the snippet with all attributes in one line.

**Comment by angelozerr** [comment]
Same issue than https://github.com/eclipse/lemminx/issues/690
