### ISSUE TITLE
[xml-model] Snippet to generate xml-model

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx#699]
Snippet to generate xml-model and their attributes (with choice). See https://www.w3.org/XML/2010/01/xml-model/

To do that:

 * rename `prolog-snippets.json` to `processing-instruction-snippets.json`
 * write xml-model snippets in `processing-instruction-snippets.json`.

**Comment by BalduinLandolt** [comment]
I'll give that a go, if that's allright and no one is working on it already?

**Comment by angelozerr** [comment]
@datho7561 should work on this issue, but i think he has not started it. @datho7561 if you have not started something, are you OK to delegate this issue to @BalduinLandolt ?

**Comment by datho7561** [comment]
I haven't started working on this issue, and I'm okay with @BalduinLandot working on it.

**Comment by angelozerr** [comment]
> I haven't started working on this issue, and I'm okay with @BalduinLandot working on it.

Thanks @datho7561 for your answer.

@BalduinLandolt any contribution are welcome! I think we should have a snippets with required attribute like href and another (one or several) snippets with other attributes. Some attributes like schematypens should be declared as choice to have a list of values.

**Comment by BalduinLandolt** [comment]
Allright then. :)

In fact, I'd rather leave the prolog snippet as it is, and make processing insructions a separate on. That is for two reasons:
1) the prolog is technically not a PI (see #727)
2) the PIs have different rules, where they can be triggered: the prolog can basically only be in the first position. the PIs can be everywhere before the root element, except before the prolog.

... unless, of course, there are objections to that?  
I'll just give it a go, and then draft a PR. If you don't like it, you'll see that right away, there.
