### ISSUE TITLE
CodeAction to create missing noNamespaceSchemaLocation and generate XSD that adheres to current XML

### ISSUE THREAD

**Issue by xorye** [eclipse/lemminx#702]
This issue is an extension to https://github.com/eclipse/lemminx/issues/691

https://github.com/eclipse/lemminx/issues/691 implements a new code action to create a new missing XSD file with generic content (prolog). This issue is to improve upon this, by generating XSD that adheres to the newly created XSD file's corresponding XML.

**Comment by angelozerr** [comment]
For your information, @xorye I have started to experiment to generate XSD from XML files and DTD from XML files. See my branch at  https://github.com/angelozerr/lemminx/tree/grammar-generator2

**Comment by angelozerr** [comment]
Fixed with https://github.com/eclipse/lemminx/issues/778
