### ISSUE TITLE
Fix error range TargetNamespace.2

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx#703]
This issue occurs when xml-model support will be merged.

Given this XML :

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-model href="http://www.docbook.org/xml/5.0/xsd/docbook.xsd"?>
<book> 
	<title />
  	<BAD_ELEMENT />
</book> 
```

We have this error:

![image](https://user-images.githubusercontent.com/1932211/81974089-5b6c4500-9625-11ea-8d19-098cfbeae3e5.png)

We should:

  * fix error range, instead of highlight ?, we must highlight `book` root element.
 * provide a code action, to insert in the book the text `xmlns="http://docbook.org/ns/docbook"`

**Comment by datho7561** [comment]
I am working on resolving this issue.
