### ISSUE TITLE
Fix error range TargetNamespace.1

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx#704]
This issue occurs when xml-model support will be merged.

Given this XML :

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-model href="http://www.docbook.org/xml/5.0/xsd/docbook.xsd"?>
<book xmlns="BAD_NS"> 
	<title />
  	<BAD_ELEMENT />
</book> 
```

We have this error:

![image](https://user-images.githubusercontent.com/1932211/81974647-257b9080-9626-11ea-8daf-8412c6711cb0.png)

We should:

  * fix error range, instead of highlight >, we must highlight `BAD-NS` attribute value of xmlns.
 * provide a code action, to replace `BAD_NS` with `http://docbook.org/ns/docbook`

**Comment by datho7561** [comment]
I would be interested on working on this
