### ISSUE TITLE
Avoid duplicate of snippet label

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx#710]
Today snippet uses prefix as label, but it causes duplicate of completion label:

![image](https://user-images.githubusercontent.com/1932211/82326087-9af7b000-99dc-11ea-9476-b06a76f3774f.png)

The prefix is used as label like vscode does with their snippet. The idea is to keep this default behavior and add a new JSON field like `useDescriptionAsLabel: true`

@fbricon what do you think about this idea?

**Comment by fbricon** [comment]
or we could add an optiona label field, that can resolve items like $prefix, $description,
having "label":"$description" by default, you can override it with "label":"Whatever" or "label":"$prefix - $description"
 
in Java you'd do String label = theLabel.replaceAll("$prefix", prefix).replaceAll("$description", description)...

**Comment by fbricon** [comment]
actually using $ requires escaping when calling replaceAll, so be careful

**Comment by angelozerr** [comment]
> or we could add an optional label field, that can resolve items like $prefix, $description

Good idea, I implemented your idea in my PR.
