### ISSUE TITLE
completionRequest.getReplaceRange() is erroneous in text that contains /

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lemminx#723]
In LemMinX extensions, `CompletionParticipantAdapter.onXMLContent`, when on a node that contains `/` (eg `path/to/something`), then `request.getReplaceRange()` returns only the offset location (resulting in an insertion) while in other cases, it returns the whole text node area (which allows filtering and replacement).
I would expect to always get the whole text node range.
If it's not possible to always have the whole text node range, then it should always be the offset; or whatever over sane convention as long _it's always the same one_.

**Comment by angelozerr** [comment]
Indeed it's a bug. The replace range for text node should be the full text content.

**Comment by angelozerr** [comment]
I think the bug is https://github.com/eclipse/lemminx/blob/2aad97f8bb81ff447d9d44acd02c3df0bc3ea841/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/services/XMLCompletions.java#L756

Before this line, you should compute the proper replace range 

```java
Range textRange = ...
request.setReplaceRange(textRange);
```
