### ISSUE TITLE
Rename "processing instruction" snippet to "xml declaration"

### ISSUE THREAD

**Issue by BalduinLandolt** [eclipse/lemminx#727]
this is totally minor, I just stumbled across it:  
The snippet for the prolog is called "processing instruction":

https://github.com/eclipse/lemminx/blob/b0dd7ce255def2ec4311cc94138f2d9064fb0029/org.eclipse.lemminx/src/main/resources/org/eclipse/lemminx/services/snippets/prolog-snippets.json#L2

But technically, this is the "XML Declaration" and not a processing instruction as such. (At least according to Wikipedia: https://en.wikipedia.org/wiki/Processing_Instruction)

**Comment by angelozerr** [comment]
I agree, it should be renamed to `Insert xml declaration`
