### ISSUE TITLE
xml-stylesheet snippet

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx#728]
Manage snippet for generating xml-stylesheet processing instruction.

To do that:

 * rename `prolog-snippets.json` to `processing-instruction-snippets.json`
 * write xml-stylesheet snippets in `processing-instruction-snippets.json`.

**Comment by BalduinLandolt** [comment]
I could do that (should be easier by now... ^^).

I guess the "rename" bit is obsolete now. But adding the snippets should be fairly straight forward.  
(Note to self: https://www.w3.org/TR/2010/REC-xml-stylesheet-20101028/)

**Comment by BalduinLandolt** [comment]
@angelozerr (or anybody else who can, for that matter) if no one is working on it, feel free to assign me and I'll do it

**Comment by angelozerr** [comment]
Thanks @BalduinLandolt !
