### ISSUE TITLE
Entity documentation has no value for entities declared with SYSTEM OR PUBLIC

### ISSUE THREAD

**Issue by xorye** [eclipse/lemminx#741]
With this XML

```
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE copyright [
  <!ELEMENT copyright (#PCDATA)>
  <!ENTITY c SYSTEM "http://www.xmlwriter.net/copyright.xml">
]>
<copyright>&c;</copyright>
```
The hover does not show the value of c:
![image](https://user-images.githubusercontent.com/20326645/83178745-f87fb100-a0ee-11ea-83c4-439add087ace.png)

The same thing happens if we have 
`<!ENTITY c PUBLIC "http://www.xmlwriter.net/copyright.xml">`
instead of
`<!ENTITY c SYSTEM "http://www.xmlwriter.net/copyright.xml">`

It would be great if the entity's value (`"http://www.xmlwriter.net/copyright.xml"` in this case) was displayed in the documentation.

**Comment by fbricon** [comment]
Is this the expected result?

<img width="563" alt="Screen Shot 2020-05-30 at 9 30 10 PM" src="https://user-images.githubusercontent.com/148698/83337549-c6bc4500-a2bc-11ea-9b86-27ca646d26a8.png">

http://www.xmlwriter.net/copyright.xml doesn't exist. Does it change anything, isn't it supposed to be actually read for the actual entity resolution?

**Comment by angelozerr** [comment]
I need to Read spécification but xerces doesnt report error with entity  copyright so i think its a vazlid entity. For résolution support please create an issue
