### ISSUE TITLE
Tests fails when basedir has space

### ISSUE THREAD

**Issue by BalduinLandolt** [eclipse/lemminx#749]
https://github.com/eclipse/lemminx/blob/3342ed0357b49003a0152ffd4d421c28ea30fec3/org.eclipse.lemminx/src/test/java/org/eclipse/lemminx/extensions/contentmodel/DTDCompletionExtensionsTest.java#L196-L207

On my end, this test keeps failing. The link to the DTD seems to be dead (as SVG 1.0 is not a thing anymore), and therefor the schema-based completions don't work anymore.  
Also it seems to wayt for a timeout, because this one test takes more than 15 seconds.

Am I goofing, or is this test just broken?

**Comment by angelozerr** [comment]
Test are working because CI build is working.

This test uses a XML catalog where the svg DTD is declared https://github.com/eclipse/lemminx/blob/3342ed0357b49003a0152ffd4d421c28ea30fec3/org.eclipse.lemminx/src/test/resources/catalogs/catalog.xml#L24 and should use the `src\test\resources\dtd\svg.dtd` 

What is your result of test?

**Comment by BalduinLandolt** [comment]
Well, clearly something with the unit test is botched on my end... With Java 11 I got around 110 failing tests. Now I switched to Java 8 (which vs code java extension doesn't seem to like too much) and I get 31 failed tests.  
(Most of the failed tests are in `FilePathCompletionTest` but some others fail too.)

But that's clearly on my end, so it doesn't need to be an issue here.

**Comment by angelozerr** [comment]
@BalduinLandolt could you share your JUnit report please.

**Comment by BalduinLandolt** [comment]
Sure.  
(I didn't figure out how to get the report from vs code, so here's what I exported from intellij.)
[report.zip](https://github.com/eclipse/lemminx/files/4755528/report.zip)

looking at it briefly, most of them seem to be:
```
java.net.URISyntaxException: Illegal character in path at index 24: file:///C:/Users/Balduin Landolt/Documents/smartgit_repos/lemminx/org.eclipse.lemminx/target/temp/note.dtd
	at java.base/java.net.URI$Parser.fail(URI.java:2915)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3086)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3168)
	at java.base/java.net.URI$Parser.parse(URI.java:3116)
	at java.base/java.net.URI.&amp;lt;init&amp;gt;(URI.java:600)
	at org.eclipse.lemminx.extensions.contentmodel.BaseFileTempTest.createFile(BaseFileTempTest.java:60)
```
Basically, the space in the file path seems to cause an exception at
```
at org.eclipse.lemminx.extensions.contentmodel.BaseFileTempTest.createFile(BaseFileTempTest.java:60)
```
So it's very much something that is my fault, but also something that might be an actual bug, because other people could also have spaces in their file paths.

I'll look at it again in more depth, as soon as I have time, and will keep you updated.
