### ISSUE TITLE
CacheResourcesManagerTest.testAvailableCache fails sometimes

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx#753]
The Junit test CacheResourcesManagerTest.testAvailableCache fails sometimes in CI build. I suspect that several PR uses the same folder to check file is not downloaded. I think teh fix is to use a temporar file to download XSD, DTD files to test.

**Comment by datho7561** [comment]
I'd be interested in investigating this. It happens on my local machine as well.

**Comment by datho7561** [comment]
I was having some issues reproducing it on my local machine. On a Fedora VM where I limit the bandwidth access,  `CacheResourcesManagerTest.testUnavailableCache` fails. If I increase the cache expire time (just for the tests) to 2 seconds and wait 1 second for files to download, then it works. This will increase the test run time by a bit, but is a fiarly simple fix.

Another way to go about this (cleaner implementation, which requires a lot more changes and is probably not feasible) is to return a `CompletableFuture<Path>` in the cache's `getResource`, and refactor all the code to use futures.

**Comment by datho7561** [comment]
I tried again with `cpulimit` to limit the CPU usage to 25%, and both the available and unavailable tests failed consistently.

I also tried with `trickle` to limit download bandwidth to 1kbps. This also caused tests to fail, but not as consistently as when limiting the CPU.
