### ISSUE TITLE
XML validation should aggregate XSD errors where is referenced

### ISSUE THREAD

**Issue by datho7561** [eclipse/lemminx#768]
The error range for EmptyTargetNamespace for an .xml file that references an .xsd file with an empty target namespace is incorrect. Here is the current error range, with the warning label placed on the `model` of `<?xml-model...`:

![EmptyTargetNamespaceXML](https://user-images.githubusercontent.com/22376627/84044075-14981380-a975-11ea-9749-f6f3e1433208.png)

To reproduce, the `xmlns` attribute of the root element needs to be set to a non-empty value.

Here is some sample code to reproduce:

`twoLetterName.xsd`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="">
    <xs:element name="two-letter-name">
        <xs:simpleType>
            <xs:restriction base="xs:token">
                <xs:pattern value="[A-Z][a-z]"></xs:pattern>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
</xs:schema>
```

`twoLetterNameInstance.xml`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model
    href="twoLetterName.xsd"
    type="application/xml"
    schematypens="http://www.w3.org/2001/XMLSchema"?>
<two-letter-name xmlns="otherNamespace">Io</two-letter-name>
```

The range should instead highlight the reference to the .xsd schema file. This is because the schema file is what is causing this issue. For instance, in this case, `href="twoLetterName.xsd"` should be highlighted.

**Comment by angelozerr** [comment]
Thanks so much @datho7561 for your great review!
