### ISSUE TITLE
DTD generation: support for "optional" elements

### ISSUE THREAD

**Issue by xorye** [eclipse/lemminx#789]
Generating DTD with the DTD generator (with the code action) in this case:
```
<!DOCTYPE root PUBLIC "public-id" "file.dtd">
<root>
    <a></a>
    <a>
        <b></b>
    </a>
</root>
```

The generator generates this DTD:
```
<!ELEMENT root (a+)>
<!ELEMENT a (b)>
<!ELEMENT b EMPTY>
```

causing a validation error in the corresponding xml:
![image](https://user-images.githubusercontent.com/20326645/85149644-872fab80-b21f-11ea-815c-3cce55d0de18.png)

To have no validation errors, it would be great if the generated DTD was
```
<!ELEMENT root (a+)>
<!ELEMENT a (b)*>
<!ELEMENT b EMPTY>
```

or

```
<!ELEMENT root (a+)>
<!ELEMENT a (b*)>
<!ELEMENT b EMPTY>
```

**Comment by angelozerr** [comment]
Fixed in https://github.com/eclipse/lemminx/pull/779
