### ISSUE TITLE
XSD generation: minOccurs support

### ISSUE THREAD

**Issue by xorye** [eclipse/lemminx#790]
Generating XML schema with the XML schema generator (with the code action) in this case:
```
<root-element
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file.xsd">
    <root>
        <a></a>
        <a>
            <b></b>
        </a>
    </root>
</root-element>
```

The generator generates this XSD file:
```
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="root-element">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="root">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="a">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="b" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
```

causing a validation errors in the corresponding xml:
![image](https://user-images.githubusercontent.com/20326645/85150449-89ded080-b220-11ea-9dff-e01cff392dfd.png)

To fix the validation error on line 5, it would be great if the XSD declaration for element `b` had `minOccurs="0"` like so: `<xs:element name="b"  minOccurs="0"/>`.

The error on line 6 is caused by https://github.com/eclipse/lemminx/issues/788

**Comment by angelozerr** [comment]
Fixed in https://github.com/eclipse/lemminx/pull/779
