### ISSUE TITLE
Customize documentSymbols (Outline) with participant

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx#824]
The Outline is filled with all elements without attributes and without text content.

It should be fine to customize this behavior:

 * with participant. For pom.xml lemmix-maven could display dependencies with text node content. @mickaelistria @AObuchow I think you could be interested with this feature?

 * with user settings to customize show attributes, text for given XML (pattern)

**Comment by AObuchow** [comment]
I'm +1 for this idea :)

**Comment by angelozerr** [comment]
The PR https://github.com/eclipse/lemminx/pull/895 covers this issue with the new [ISymbolsProviderParticipant](https://github.com/eclipse/lemminx/pull/895/files#diff-1a62215bdc803f58e87540341747ea9f) participant API .

@AObuchow @mickaelistria if you are intetested  with this feature please review the PR :)

**Comment by datho7561** [comment]
Closed in PR #895
