### ISSUE TITLE
Number of org.eclipse.lemminx.XMLServerLauncher increases after branch switch

### ISSUE THREAD

**Issue by thomasulllrich** [eclipse/lemminx#840]
Hi!
Everytime I switch to another branch and open an arbitrary xml file there are more java processes with the main class org.eclipse.lemminx.XMLServerLauncher started(1,3,9,14 number of Java processes). I can close the xml-file before the switch and open it afterwards or keep it open while the switch happens, it always ends up with the same number of processes. Is there a workaround or a configuration option because I don't want to restart after each branch switch my Eclispe again.
Best regards,
Thomas

**Comment by mickaelistria** [comment]
WIld Web Developer takes care of the integration of LemMinX into Eclipse IDE. So please report your issue (ideally with minimal steps to reproduce) to https://github.com/eclipse/wildwebdeveloper/issues
