### ISSUE TITLE
XML catalog nextCatalog/@catalog documentLink support. 

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx#845]
Given this XML catalog:

```xml
<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">

  <nextCatalog catalog="plugins/org.dita.base/catalog-dita.xml"/>

</catalog>
```

This sample comes from `catalog-dita.xml` from https://github.com/dita-ot/dita-ot/releases/download/3.5.1/dita-ot-3.5.1.zip

It should be nice to have hyperlink for nextCatalog /@catalog attribute

**Comment by datho7561** [comment]
I would be interested in working on this. Ideally, all the elements that refer to another catalog (have a `catalog` attribute that's a URI) that are defined in the catalog schema should have document links. These are:
 * `delegatePublic`
 * `delegateSystem`
 * `delegateUri`
 * `nextCatalog`

[Reference to the catalog XSD schema](https://www.oasis-open.org/committees/download.php/14809/xml-catalogs.html#a.w3cxmlschema)
