### ISSUE TITLE
Can you configure the location of the Lemmix cache?

### ISSUE THREAD

**Issue by willrogers** [eclipse/lemminx#851]
I am trying to do development with Eclipse and Maven.

The m2e plugin has apparently caused downloaded almost 1G into `~/.lemminx/cache` and exceeded my filesystem quota.

Is there any way to configure where Lemminx puts its cache?

**Comment by angelozerr** [comment]
XML Language Server can configure that with `xml.server.workDir`. Here the whole supported settings https://github.com/redhat-developer/vscode-xml#supported-vs-code-settings

As you are using Eclipse I suppose you are using WilWebDeveloper. I suggest you that you create an issue to support this preference.

**Comment by fbricon** [comment]
@AObuchow what does lemminx-maven put in ~/.lemminx/cache?

**Comment by AObuchow** [comment]
@fbricon I don't remember us explicitly creating the cache but maybe I forgot... Looking at its contents, the cache seems to contain .dtd and .xsd files for Maven Poms.

@willrogers are you certain it's `~/.lemminx/cache/` that is taking up 1gb of space? The large download is caused by downloading the Maven central index, which is supposed to download into `~/.lemminx/index/ `

**Comment by angelozerr** [comment]
See https://github.com/eclipse/lemminx-maven/blob/4857015142ff1b2b9be2be845b9831a3f26d5b28/lemminx-maven/src/main/java/org/eclipse/lemminx/maven/searcher/RemoteRepositoryIndexSearcher.java#L79

And it seems that you can configure with `-lemminx.maven.indexDirectory` env

**Comment by mickaelistria** [comment]
If this is about specific Maven integration, please bring this issue to https://github.com/eclipse/lemminx-maven as there is nothing lemminx "core" can do about it.

**Comment by willrogers** [comment]
I have opened https://github.com/eclipse/lemminx-maven/issues/130 to try to track this, thanks.

**Comment by kuniss** [comment]
Just a question, I did not found answered anywhere in the net related to this here: 
Where does the configuration file for lemmix is located for the Eclipse integrated LS? Where the LS is looking for it? What's its name?

Thanks in advance for answering it!
