### ISSUE TITLE
Make XMLAssert class available to external extensions

### ISSUE THREAD

**Issue by kathrynkodama** [eclipse/lemminx#868]
We would like to use the [XMLAssert](https://github.com/eclipse/lemminx/blob/d2d5bb76a1309f6d52bd8177d08aecbfafa5b5fb/org.eclipse.lemminx/src/test/java/org/eclipse/lemminx/XMLAssert.java) class to write tests for the [Liberty LemMinX extension](https://github.com/OpenLiberty/liberty-language-server/tree/master/lemminx-liberty)

**Comment by fbricon** [comment]
Yes ;-)
