### ISSUE TITLE
Improve error range for ETagUnterminated 

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx#875]
Given this XML file:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<project>
  <dependencies>
    <dependency>
      <scope>test</scope>
    </dependency
    <dependency>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
```

The error highlight scope element:

![image](https://user-images.githubusercontent.com/1932211/93319311-05482200-f810-11ea-9726-e053d85a948f.png)

although it should higlight the dependency element like:

![image](https://user-images.githubusercontent.com/1932211/93319394-1abd4c00-f810-11ea-822e-e165575b4c1e.png)

Another usecase:

```xml
<foo>
  <ba><ABCD></ABCD></bar>
</foo>
```

`bar` should be highlighted, but we have that:

![image](https://user-images.githubusercontent.com/1932211/93320611-8fdd5100-f811-11ea-94ac-dcbfd5a9ac23.png)

**Comment by fbricon** [comment]
Weird, cause it works in other cases
<img width="815" alt="Screen Shot 2020-09-16 at 12 14 24 PM" src="https://user-images.githubusercontent.com/148698/93324508-4cd1ac80-f816-11ea-9f8a-dada69b1a99a.png">

**Comment by angelozerr** [comment]
> Weird, cause it works in other cases

Yes I know, we support error range for ETagUnterminated, but there are some usecases (described in the issue) which doesn't work. I started to investigate the problem, hope I could create a PR soon.
