### ISSUE TITLE
Improve ETagRequired error range

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx#876]
Given this XML file:

```xml
<foo>
  <bar></
</foo>
```

We have that:

![image](https://user-images.githubusercontent.com/1932211/93320119-f877fe00-f810-11ea-8bbd-a58af592251d.png)

Although the ETagRequired error range should highlight the start tag element:

**Comment by fbricon** [comment]
Weird, cause it works in other cases
<img width="815" alt="Screen Shot 2020-09-16 at 12 14 24 PM" src="https://user-images.githubusercontent.com/148698/93324508-4cd1ac80-f816-11ea-9f8a-dada69b1a99a.png">
