### ISSUE TITLE
Error range for MarkupNotRecognizedInProlog

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx#879]
Given this XML file:

```xml
</foo>
```

The error range should higlight foo, today we have:

![image](https://user-images.githubusercontent.com/1932211/93600803-82b29480-f9c0-11ea-85e6-9df09e016d47.png)

**Comment by angelozerr** [comment]
After studying this usecase, I think the error range is correct because the xerces error report this offset and this error is reported too with just `</`

**Comment by fbricon** [comment]
Ok sounds legit. Closing.
