### ISSUE TITLE
Remove content from wiki 

### ISSUE THREAD

**Issue by rzgry** [eclipse/lemminx#888]
https://github.com/eclipse/lemminx/pull/882 moved the content from the wiki to the repo itself to allow for external contributors.(https://github.com/eclipse/lemminx/tree/master/docs) I think it makes sense to remove the content from https://github.com/eclipse/lemminx/wiki so it does not need to be maintained in 2 separate places.

**Comment by angelozerr** [comment]
+1

**Comment by datho7561** [comment]
I removed the content from the wiki, added a link to `docs/`, and added short explanation as to why this was done.
