### ISSUE TITLE
Code Action for `</` with no matching open tag

### ISSUE THREAD

**Issue by datho7561** [eclipse/lemminx#889]
A code action is suggested in this case:
```xml
<a></</a>
```
The code action adds a closing tag (`</a`) right after `<a>`, but I would expect it to remove `</`:
![OddCloseTagCodeAction](https://user-images.githubusercontent.com/22376627/94198838-e6880200-fe85-11ea-98ec-2f8546315157.gif)

**Comment by angelozerr** [comment]
Fixed with https://github.com/eclipse/lemminx/pull/897
