### ISSUE TITLE
Outline should display referenced DTD / XSD from the current XML

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx#892]
It should be really fine if outline could display the referenced DTD / XSD and their dependencies from the current XML file.

We must provide a settings to do that.

**Comment by fbricon** [comment]
Sounds overkill to me. Why would you need that?

**Comment by angelozerr** [comment]
At first I had this idea when I though how to implement https://github.com/redhat-developer/vscode-xml/issues/284#issuecomment-697156583 I need to retrieve references of XSD / DTD and their dependencies. We will see which XSD / DTD files will be removed when cache will be evicted.

The second idea is that it will help user to check that XML file is bound correctly with a XSD / DTD and with which kind binding is done (xml file associations, xml catalog, schemaLocation, xml-model, etc).

If outline doesn't display those kind of informations, user will see that it doesn't work.

**Comment by fbricon** [comment]
let's say I open a pom.xml, what does the outline look like if both the xml and xsd structure are displayed?

**Comment by angelozerr** [comment]
Here my idea:

![image](https://user-images.githubusercontent.com/1932211/94274402-f8c97500-ff45-11ea-8708-753225fc9717.png)

**Comment by fbricon** [comment]
Ok, I misunderstood the idea. Sounds good
