### ISSUE TITLE
Can't use XML catalog with XSD files that have <xs:include />

### ISSUE THREAD

**Issue by rnathuji** [eclipse/lemminx#914]
While using the [XML catalog with XSD](https://github.com/redhat-developer/vscode-xml/blob/master/docs/Validation.md#xml-catalog-with-xsd) configuration with the `vscode-xml` plugin, we encountered an issue where XSD files that utilize `<xs:include />` tags don't work. Take, for example, the following `test.xml` with `test.xsd` which includes `test-include.xsd`:

**`test.xml`**

```xml
<?xml version="1.0" encoding="UTF-8"?>
<document xmlns="http://foobar.com/test">
  <page>
    <title>Page 1</title>
    <content>Content for page 1</content>
  </page>
  <page>
    <title>Page 2</title>
    <content>Content for page 2</content>
  </page>
</document>
```

**`test.xsd`**

```xml
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://foobar.com/test" xmlns:test="http://foobar.com/test">
  <xs:include schemaLocation="test-include.xsd"/>
</xs:schema>
```

**`test-include.xsd`**

```xml
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://foobar.com/test" xmlns:test="http://foobar.com/test">
  <xs:element name="document">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="test:page"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="page" type="test:page-content"/>
  <xs:complexType name="page-content">
    <xs:sequence>
      <xs:element ref="test:title"/>
      <xs:element ref="test:content"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="title" type="xs:string"/>
  <xs:element name="content" type="xs:string"/>
</xs:schema>
```

With a catalog definition as follows:

**`test_catalog.xml`**

```xml
<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
  <uri
      name="http://foobar.com/test"
      uri="./test.xsd" />
</catalog>
```

Opening `test.xml` results in:

```
cvc-elt.1.a: Cannot find the declaration of element 'document'.
```

A "merged" `test-merged.xsd`, however, works just fine:

**`test-merged.xsd`**

```xml
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://foobar.com/test" xmlns:test="http://foobar.com/test">
  <xs:element name="document">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="test:page"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="page" type="test:page-content"/>
  <xs:complexType name="page-content">
    <xs:sequence>
      <xs:element ref="test:title"/>
      <xs:element ref="test:content"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="title" type="xs:string"/>
  <xs:element name="content" type="xs:string"/>
</xs:schema>
```

It seems this may be due to the way resolution occurs in `XMLCatalogResolver` based [upon the namespace](https://github.com/apache/xerces2-j/blob/cf0c517a41b31b0242b96ab1af9627a3ab07fcd2/src/org/apache/xerces/util/XMLCatalogResolver.java#L418) when invoked [here](https://github.com/eclipse/lemminx/blob/af09659c7ca4998fac87e1027de644a4167a4102/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/uriresolver/XMLCatalogResolverExtension.java#L86). As a quick test to help confirm the root cause, we did find that making a similar change as the one in this related [SO post](https://stackoverflow.com/questions/9969773/can-xerces-support-xmlcatalogresolver-and-xsinclude-at-the-same-time) to `resolveEntity` in `XMLCatalogResolverExtension.java` seemed to correct the problem.

**Comment by angelozerr** [comment]
@rnathuji thank a lot for reporting this issue and give us a very detailed information.

Is there any chance to have a PR and tests with your suggestion fix?

**Comment by rnathuji** [comment]
@angelozerr - Sure, I'd be happy to help with a PR. I may, however, need some guidance due to my lack of familiarity 😅 . I've created a [draft PR](https://github.com/eclipse/lemminx/pull/917) for the time being which contains the quick and dirty change that allowed things to work while debugging / testing. I'd definitely welcome feedback as far as.

1. Whether this is even the proper place to try and hook this logic in
2. The use of `resourceIdentifier.getExpandedSystemId() != null` as a conditional gate -- It feels brittle to me in that I don't know what underlying assumptions that makes

I can also start looking at the test additions, but LMK if there are any major course corrections that should be made in terms of the implementation approach.
