### ISSUE TITLE
When associating a DTD through <?xml-model...?>, DTD-related errors should be aggregated

### ISSUE THREAD

**Issue by datho7561** [eclipse/lemminx#918]
Please refer to issue #768 and [this comment](https://github.com/eclipse/lemminx/pull/916#issuecomment-714575637) on the PR that addresses it.

When a DTD is associated with a file through `<?xml-model...?>`, and errors exist on the associated DTD, an error message should be shown. The current behaviour is that a "file not found" error is given:
![ReferencesBorkedDTDXMLModel](https://user-images.githubusercontent.com/22376627/96921515-a3b54c00-147c-11eb-8f48-e8c7c24d4e62.png)

This error should instead indicate that the DTD is invalid. Ideally, this error should also be an aggregation of the DTD errors like in #768.

Quick example to reproduce this issue:

`ReferencesBorked.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="Borked.dtd" type="application/xml-dtd"?>
<root>
</root>
```

`Borked.dtd`:
```dtd
<!ELEMENT root (branch+)>
<!ELEMENTbranch (#PCDATA)>
```

**Comment by angelozerr** [comment]
Fixed with https://github.com/eclipse/lemminx/pull/916
