### ISSUE TITLE
TargetNamespace not accepted in file association

### ISSUE THREAD

**Issue by yatli** [eclipse/lemminx#935]
Hi!

I'm still trying to work out the MSBuild use scenario.
Their schema is not retrievable at http://schemas.microsoft.com/developer/msbuild/2003, but they do provide xsd targeting the namespace.

As of v0.14.1 I'm still hitting the error:
```
[xml TargetNamespace.2] [E] TargetNamespace.2: Expecting no namespace, but the schema document has a target namespace of 'http://schemas.microsoft.com/developer/msbuild/2003'.
```

A sample xml file:
[fvim.zip](https://github.com/eclipse/lemminx/files/5565153/fvim.zip)

Various xsd files:
[xsd.zip](https://github.com/eclipse/lemminx/files/5565149/xsd.zip)

File association configuration: something like this:

```json
    "xml.fileAssociations": [
        {
            "systemId": "C:/Users/Yatao/AppData/Local/nvim/xsd/MSBuild/Microsoft.Build.Commontypes.xsd",
            "pattern": "**/*.fsproj"
        }
    ],

```

**Comment by angelozerr** [comment]
Your error is normal. The XSD declares targetNamespace="http://schemas.microsoft.com/developer/msbuild/2003", it means that your XML must defines this namespace `xmlns="http://schemas.microsoft.com/developer/msbuild/2003"` like this:

`<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" Sdk="Microsoft.NET.Sdk"  >`

You have a quick fix which does that. See the following demo:

![FSProjDemo](https://user-images.githubusercontent.com/1932211/99673920-9c7e5f80-2a75-11eb-8655-297eb5031e50.gif)

**Comment by yatli** [comment]
![coc-xml](https://user-images.githubusercontent.com/20684720/99698972-64eed200-2acc-11eb-9224-b184713e84d4.gif)

Thank you!

**Comment by angelozerr** [comment]
> Thank you!

Very nice:) Quick fixes are your friend.
