### ISSUE TITLE
Disabling schema validation on one specific file/project/workspace?

### ISSUE THREAD

**Issue by glhez** [eclipse/lemminx#951]
Hello,

I am trying to edit an Oomphs Setup file using the XML editor rather than Oomphs own editor because it is faster for certain task (like copy/pasting P2 repositories).

The setup file contains more or less the following: notice the namespace and its location `http://git.eclipse.org/c/oomph/org.eclipse.oomph.git/plain/setups/models/Workbench.ecore`:

```xml 
<?xml version="1.0" encoding="UTF-8"?>
<setup:Configuration
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:setup="http://www.eclipse.org/oomph/setup/1.0"
    xmlns:setup.p2="http://www.eclipse.org/oomph/setup/p2/1.0"
    xmlns:workbench="http://www.eclipse.org/oomph/setup/workbench/1.0"
    xsi:schemaLocation="http://www.eclipse.org/oomph/setup/workbench/1.0 http://git.eclipse.org/c/oomph/org.eclipse.oomph.git/plain/setups/models/Workbench.ecore"
    label="Gael Eclipse Installation"> 
  <installation name="com.github.glhez.eclipse.install" label="Gael Eclipse Installation Installation">
    <setupTask xsi:type="setup.p2:P2Task" label="Oomph Setup Task">
      <requirement name="org.eclipse.oomph.setup.feature.group"/>
      <repository url="${oomph.update.url}"/>
    </setupTask> 
    <!-- a lot of stuff here -->
   </installation>
</setup:Configuration>
```

The XML Language Server, provided by Wild Web Developer XML tools (0.10.3.202011132012) in my fresh Eclipse 2020.12 (using Oomphs :)) is reacting to the namespace with this particular error (whose Type is Language Servers in Eclipse Problems view):

> schema_reference.4: Failed to read schema document 'http://git.eclipse.org/c/oomph/org.eclipse.oomph.git/plain/setups/models/Workbench.ecore', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.

The *.ecore file is effectively not a schema.

And since Xerces (?) can't read the schema as a schema, then it fails due to missing types:

> cvc-elt.1.a: Cannot find the declaration of element 'setup:Configuration'.
> cvc-elt.4.2: Cannot resolve 'setup:CompoundTask' to a type definition for element 'setupTask'.

This gives me 25 errors for one missing schema. And I loathe error in my code!

Disabling the XML Language Server is probably possible, but as far I tested, it does not work without restarting the IDE which is not something that I want: 

- I could have XML file that I want to validate
- ... and other like this one that I can't validate
- and beside validation, is the tooling the language server provides (refactor, completion, ....)

I very would like a way to disable schema validation on this file, or its project, or when there is a schema validation error, that only one error is reported.

**Comment by fbricon** [comment]
might be a problem with http=>https redirection being ignored by lemminx. Try changing the eclipse urls to https

**Comment by fbricon** [comment]
As for disabling XML validation, `"xml.validation.enabled": false` is preference supported by LemMinX, but prolly not exposed by Wild Web Developer, which makes it a WWD issue.

**Comment by angelozerr** [comment]
To fix this issue, LemMinx should:

 * ignore the load of the ecore schemaLocation
 * or provides the capability to load a Grammar from an ecore (I think it can be hard).

**Comment by glhez** [comment]
> might be a problem with http=>https redirection being ignored by lemminx. Try changing the eclipse urls to https

Tried with https: no success.

The "schema" is loaded, but is really invalid : it is not a valid XML schema. It is proper to Eclipse.

> As for disabling XML validation, `"xml.validation.enabled": false` is preference supported by LemMinX, but prolly not exposed by Wild Web Developer, which makes it a WWD issue.

I'll create an issue with them. I assume this preference can be per file/project and that it is sent during a XML validation ?

**Comment by angelozerr** [comment]
> The "schema" is loaded, but is really invalid : it is not a valid XML schema. It is proper to Eclipse.

I don't if it will be easy to integrate EMF validation in WWD with a LemMinX extension?

> I'll create an issue with them. I assume this preference can be per file/project and that it is sent during a XML validation ?

XML Language Server LemMinX doesn't support this settings kind, we should improve it. For the moment it's just a global validation settings.

**Comment by fbricon** [comment]
@angelozerr there might be a way to do some file association with https://raw.githubusercontent.com/cloudsmith/org.eclipse.emf/master/plugins/org.eclipse.emf.ecore/model/Ecore.xsd

**Comment by angelozerr** [comment]
@fbricon let me study WTP XML editor validator which doesn't report error with this file. LemMinX should have the same behavior.

**Comment by angelozerr** [comment]
I created a PR https://github.com/eclipse/lemminx/pull/953 which have the same behavior than WTP XML validator, in otherwise as `http://www.eclipse.org/oomph/setup/1.0` (which is used for root element setup:Configuration) is not declared, the XSD validation is disabled.

**Comment by angelozerr** [comment]
Fixed with https://github.com/eclipse/lemminx/pull/953
