### ISSUE TITLE
How can an extension know the "workspaceFolders" that are known by the LS (passed from client)?

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lemminx#955]
In order to implement https://github.com/eclipse/lemminx-maven/issues/77 , we need the LemMinX Maven extension to be informed about which workspaceFolders are passed by the client, so the extension can inspect those workspace folders during resolution.

I looked a bit in the code of lemminx-maven and only found issue #293 . Do I get it right that at the moment, workspaceFolders are not used nor stored in the LS and that there is no way for extensions to retrieve them?

**Comment by angelozerr** [comment]
To be honnest with you, I don't know how to implement this support, but it exists an old PR for that https://github.com/eclipse/lemminx/pull/293

**Comment by mickaelistria** [comment]
I looked at #293 and it doesn't seem to contain that part of the story. #293 is more about managing capabilites, while here it's more from an extension perspective.
I think there could be a WorkspaceFolderParticipant that could be attached to the Language Service to receive notifications about workspace change (eg 1 project was added/removed). Does that seem a viable approach?

**Comment by mickaelistria** [comment]
I'm closing this discussion as a solution is being implemented in #958
