### ISSUE TITLE
Do an Eclipse release review

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lemminx#995]
LemMinX did not participate in a release review, while Eclipse Development Process mandates at least 1 release review per year. This is becoming a concern, see https://www.eclipse.org/lists/tools-pmc/msg05151.html .
Please plan a release review soon to show that LemMinX is playing by the rules of Eclipse Development Process.

**Comment by rgrunber** [comment]
We should create/update the release plan for the upcoming 0.15.1 as described in https://www.eclipse.org/projects/handbook/#releases-plan .

We could also double-check the items in https://www.eclipse.org/projects/handbook/#checklist .

**Comment by rgrunber** [comment]
So we've got the [0.16.0 Review Documentation](https://projects.eclipse.org/projects/technology.lemminx/releases/0.16.0) , the [IPLog](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23070) , so we'll just need to request PMC Approval (which goes to the pmc mailing list) and then we can start the review.

**Comment by datho7561** [comment]
Before requesting PMC approval, should we push in a PR that includes `<name>` and `<organization>`?

**Comment by rgrunber** [comment]
> Before requesting PMC approval, should we push in a PR that includes `<name>` and `<organization>`?

Yes, please do. `<name>` makes sense. If you want to do `<organization>` you can do that as well, but I have seen projects that don't.

**Comment by datho7561** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=572192

**Comment by datho7561** [comment]
https://github.com/eclipse/lemminx/releases/tag/0.16.0
